### ISSUE TITLE
align names on browse and package pages

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#1052]
sometimes the names we list on the browse page are different than the package page
we should align these

some examples:
- elastic is ec on the browse page and ElasticCloud (EC) on the package page
- artifactory is artifactory on the browse page and Artifactory on the package page
- astra is astra on the browse page and Astra on the package page
- awsx is awsx on the browse page and AWSx on the package page
- miniflux is Miniflux on the browse page and AWS Miniflux on the package page

questions:
- why do we have different metadata for these things, can they be the same?

related issues:
- https://github.com/pulumi/registry/issues/839

**Comment by lukehoban** [comment]
I do agree things are fairly "weird" here today.  

A few thoughts:
1. Should we require a display name for all packages?  If not, should we just *only* use the raw package name for all packages?
2. If no to both of the above, should we always show the raw package name in addition to display name when it is available?
3. Is there a 3rd piece of metadata?  How is it that Elastic Cloud is named named "ec" on the index page but "ElasticCloud (EC)" on the description page?

**Comment by susanev** [comment]
for the most part this is now done. we still don't have a single source of truth for this, but the two pieces of data is now fixed.

for anyone else who comes across this...
- browse page uses display name for the package if it exists, otherwise it uses the package name from the meta data; but there are exceptions here: https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/gen.go#L57-L152 which controls the name that shows on the browse page
- for the package page, the name comes from the title in the meta data which is in this repo
