### ISSUE TITLE
Add the confluent logo to the Registry

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/registry#1086]
File: [themes/default/content/registry/packages/confluentcloud/api-docs/_index.md](https://www.pulumi.com/registry/packages/confluentcloud/api-docs/
![Confluent Logo](https://user-images.githubusercontent.com/59850911/174136632-182d6b84-283d-4814-9482-0880c84e76aa.png)
)

**Comment by susanev** [comment]
@isaac-pulumi are you asking for the two different confluent providers to have two different logos?

**Comment by isaac-pulumi** [comment]
@susanev This specific provider has no logo. Confluent asked for this one.

**Comment by susanev** [comment]
right yes i know that ones not showing a logo, but seems a bit strange to use two different logos. would you be okay with us using the same logo?

the one here: https://www.pulumi.com/registry/packages/confluent/

if not, can you please ask them for a logo intended for a light background?

**Comment by isaac-pulumi** [comment]
@susanev - I'll ask for one with a light background

**Comment by susanev** [comment]
to clarify, we dont want a logo with a background at all. we want a logo that works on a light background. can you find out why they don't like the logo on the other confluent package?

**Comment by susanev** [comment]
this is no longer relevant as a new issue was created for this.
