### ISSUE TITLE
Casing issue in TypeScript example

### ISSUE THREAD

**Issue by radiomime** [pulumi/registry#1143]
File: [themes/default/content/registry/packages/gcp/api-docs/serviceAccount/account/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/)

The example usage for Typescript in the service account should be updated to be lowercase:

```typescript
const serviceAccount = new gcp.serviceAccount.Account("service_account", {
    accountId: "service-account-id",
    displayName: "Service Account",
});
```

should be

```typescript
const serviceAccount = new gcp.serviceaccount.Account("service_account", {
    accountId: "service-account-id",
    displayName: "Service Account",
});
```

Error message when running given example:
```sh
index.ts(36,40): error TS2339: Property 'serviceAccount' does not exist on type 'typeof import(".../node_modules/@pulumi/gcp/index")'.
```

**Comment by susanev** [comment]
@radiomime we are currently tracking this issue here: https://github.com/pulumi/pulumi-gcp/issues/811
so going to go ahead and close this as a duplicate
