### ISSUE TITLE
Correcting export for serviceaccount

### ISSUE THREAD

**Issue by robschn** [pulumi/registry#1196]
File: [themes/default/content/registry/packages/gcp/api-docs/serviceAccount/account/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/)

Currently, I'm getting an error because the format for `serviceaccount` from the official documentation seems off:
![Screen Shot 2022-06-30 at 10 35 57 AM](https://user-images.githubusercontent.com/13859438/176705007-8d31e1bd-80e9-43da-8ca5-386490ea23a4.png)

Making it `serviceaccount` all lowercase fixes the issue. May need to update the docs.

**Comment by susanev** [comment]
hi @robschn sry about the trouble, this issue is tracked here: https://github.com/pulumi/pulumi-gcp/issues/811
