### ISSUE TITLE
`javascript` examples are not rendered on packages page

### ISSUE THREAD

**Issue by ianaya89** [pulumi/registry#1215]
### What happened?

I set `javascript` code samples in Checkly provider docs but only `typescript` snippets are being rendered.

https://www.pulumi.com/registry/packages/checkly

### Steps to reproduce

If you check provider's registry page, the `javascript` code samples are not there but they are defined on the `md` files

- https://www.pulumi.com/registry/packages/checkly
- https://github.com/pulumi/registry/edit/master/themes/default/content/registry/packages/checkly/_index.md

I check other providers (like [Aiven](https://www.pulumi.com/registry/packages/aiven/)) and seems to have the same problem.

### Expected Behavior

Show `javascript` examples along the other languages

### Actual Behavior

`javascript` examples are ignored

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ianaya89** [comment]
@susanev thanks!

**Comment by susanev** [comment]
@ianaya89 we are going to be adding support for javascript back in. it should happen this month, but ill post here if there is a delay.

**Comment by ianaya89** [comment]
Great new, thanks!

**Comment by shughes26** [comment]
@ianaya89 Javascript code samples have been reenabled for Checkly

**Comment by ianaya89** [comment]
@shughes26 thank you :)
