### ISSUE TITLE
Update AWSX installation instructions

### ISSUE THREAD

**Issue by jkodroff** [pulumi/registry#1239]
[The AWSX setup page](https://www.pulumi.com/registry/packages/awsx/installation-configuration/) does not contain special installation instructions because the package is in beta: The user needs to both add a package explicitly and also pull down a specific version of the AWS provider if creating from e.g. `pulumi new aws-typescript`. We should add these to the page for all languages in order to ensure users have a smooth time consuming AWSX.

**Comment by stack72** [comment]
@jkodroff I don't quite understand this issue... please can you give me a little more info here of what needs fixed?

**Comment by jkodroff** [comment]
@stack72 

RE: Add a package explicitly:

Some of the package managers won't grab pre-releases by default (npm at least, possibly others). So the usual method of installation (`npm -i @pulumi/awsx`) will grab 0.40. I think we should add explicit instructions on the registry so folks can grab the 1.0 beta. `pulumi plugin install` also grabs 0.40 by default.

We (presumably) want to steer folks to the beta, since all the older TS implementation is still in `awsx-classic`, and the docs on the registry are for the 1.0 beta.

RE: Pull down a specific version of the AWS provider:

After doing `npm -i @pulumi/awsx@1.0.0-beta.7`, adding a simple `new awsx.ec2.Vpc('test');`, and running `pulumi preview`, the user gets the following error:

```
Diagnostics:
  pulumi:providers:aws (default_5_4_0):
    error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.4.0 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.4.0`
```

So I was suggesting that we add these to the AWS provider installation instructions as well to ensure that users have a smooth onboarding to the beta.

Hope that clears it up!

**Comment by stack72** [comment]
I’m pretty sure this works for beta-9 when I tried this

can you try it again?

**Comment by jkodroff** [comment]
Just to clarify, there's 2 issues:

1. It's not obvious to users how to install the 1.0 beta.
2. The installation process for the 1.0 beta isn't super smooth.

I'm assuming your comment above is referencing #2.

With these steps:

```bash
pulumi new typescript
npm i @pulumi/awsx@1.0.0-beta.9
npm i @pulumi/aws # version intentionally left off
```

And this program:

```typescript
import * as awsx from "@pulumi/awsx";

new awsx.ec2.Vpc("test");
```

`pulumi up` gives me this error:

```text
iagnostics:
  pulumi:pulumi:Stack (joshtest3-dev):
    error: [runtime] Error: failed to register new resource test [awsx:ec2:Vpc]: Resource monitor is terminating
        at Object.registerResource (/Users/jkodroff/tmp/joshtest2/node_modules/@pulumi/runtime/resource.ts:292:27)
        at new Resource (/Users/jkodroff/tmp/joshtest2/node_modules/@pulumi/resource.ts:401:13)
        at new ComponentResource (/Users/jkodroff/tmp/joshtest2/node_modules/@pulumi/resource.ts:889:9)
        at new Vpc (/Users/jkodroff/tmp/joshtest2/node_modules/@pulumi/ec2/vpc.ts:124:9)
        at Object.<anonymous> (/Users/jkodroff/tmp/joshtest2/index.ts:4:1)
        at Module._compile (node:internal/modules/cjs/loader:1105:14)
        at Module.m._compile (/Users/jkodroff/tmp/joshtest2/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/jkodroff/tmp/joshtest2/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:981:32)

  pulumi:providers:aws (default_5_4_0):
    error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.4.0 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.4.0`
```

So I think we should modify the registry installation instructions so that folks know you need to run:

```bash
npm i @pulumi/awsx@1.0.0-beta.9
npm i @pulumi/aws@5.4.0
```

Which will them resolve the error.

**Comment by stack72** [comment]
This works - I can't reproduce this I'm afraid

[![asciicast](https://asciinema.org/a/2d5TQjEVkRFI1E9L8TtyQ3jOX.svg)](https://asciinema.org/a/2d5TQjEVkRFI1E9L8TtyQ3jOX)
