### ISSUE TITLE
when interacting with the api nav it sends you to the top of the page

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#130]
## overview
when interacting with the api nav it sends you to the top of the page (this is a problem in the docs too https://github.com/pulumi/pulumi-hugo/issues/561) this is especially frustrating if you are farther down the page, and it takes you up and now what you were trying to interact with is now out of view

## expected
your position on the page does not change when you interact with the API nav

**Comment by kimberleyamackenzie** [comment]
sure, that's one option - i think we have a few different things we could play around with here to make it work, once we decide to prioritize.  i'd also propose that when we solve this, we solve it everywhere (docs left nav, api nav, and possibly the right nav - not sure if that nav ever actually gets long enough to be an issue though)- not just the api nav.
