### ISSUE TITLE
The golang example doesn't work, it's an old version

### ISSUE THREAD

**Issue by oplancelot** [pulumi/registry#1316]
File: [themes/default/content/registry/packages/azuredevops/_index.md]
```
import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	ado "github.com/pulumi/pulumi-azuredevops/sdk/v2/go/azuredevops"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		project, err := ado.NewProject(ctx, "test", &ado.ProjectArgs{
			ProjectName: pulumi.String("my-project"),
		})
		if err != nil {
			return err
		}

		return nil
	})
}
```
https://www.pulumi.com/registry/packages/azuredevops/api-docs/

The golang example doesn't work, it's an old version.
please refer to https://pkg.go.dev/github.com/pulumi/pulumi-azuredevops/sdk/v2@v2.5.0/go/azuredevops?utm_source=gopls#ProjectArgs
or
refer to api docs
https://www.pulumi.com/registry/packages/azuredevops/api-docs/

**Comment by iwahbe** [comment]
We now generate this file from upstream, and the example looks correct.
