### ISSUE TITLE
Errors when navigating to pages for resources named index

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/registry#1335]
### What happened?

There have been a couple reports of errors when attempting to navigate to registry docs for resources named `index`:  for example, see https://www.pulumi.com/registry/packages/google-native/api-docs/firestore/v1beta2/index.  It appears that Hugo is auto-magically assuming that should be an index page, and surfaces the content at https://www.pulumi.com/registry/packages/google-native/api-docs/firestore/v1beta2/, meaning that the true url errors and there is no expected index page.

### Steps to reproduce

Navigate to https://www.pulumi.com/registry/packages/google-native/api-docs/firestore/v1beta2/index - you'll see a 404.  Navigate to https://www.pulumi.com/registry/packages/google-native/api-docs/firestore/v1beta2/, and you'll see the content that is meant to be at https://www.pulumi.com/registry/packages/google-native/api-docs/firestore/v1beta2/index.

### Expected Behavior

We should be able to indicate an override of the default index behavior to Hugo.

### Actual Behavior

The expected url 404s.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ringods** [comment]
A few more of these cases:

https://www.pulumi.com/registry/packages/aws/api-docs/kendra/
https://www.pulumi.com/registry/packages/gcp/api-docs/firestore/

**Comment by susanev** [comment]
Sean fixed this, yay!
