### ISSUE TITLE
Add registrygen check to CI for community packages

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/registry#1386]
We had to revert https://github.com/pulumi/registry/pull/1375 today because the provider tag was of a version that did not have the necessary files (`_index.md` and `installation-configuration.md`) yet. When automation opens a PR, we should run registrygen as a CI check to see if any errors occur.

Relevant code in registrygen: https://github.com/pulumi/registrygen/blob/84a06167394a9b8de62bf125b294dadb14deb453/cmd/metadata/metadata.go#L252-L267

**Comment by iwahbe** [comment]
We fixed this a long time ago. We now do a full registry build on every PR.
