### ISSUE TITLE
Laungauge switch is not available

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/registry#1389]
File: [themes/default/content/registry/packages/gcp/api-docs/serviceAccount/iammember/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/iammember/)

Documentation is broken, I'm not able to switch languages, instead page shows examples in all available languages in order: nodejs, python, .NET, go, java

**Comment by stack72** [comment]
Hi @1oglop1 

My apologies for this - I just fixed up the source examples and this will get regenerated when this weeks release goes out the door :)

Paul

**Comment by stack72** [comment]
This is now live and looking way better! https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/iammember/

**Comment by 1oglop1** [comment]
@stack72 I think this is the case for the entire provider, I opened a random page and ... https://www.pulumi.com/registry/packages/gcp/api-docs/billing/accountiambinding/
