### ISSUE TITLE
Page broken (aws/wafv2/webacl)

### ISSUE THREAD

**Issue by mindejulian** [pulumi/registry#1481]
File: [themes/default/content/docs/reference/pkg/aws/wafv2/webacl/_index.md](https://www.pulumi.com/docs/reference/pkg/aws/wafv2/webacl/)

When I navigate to this page it takes forever to load, content jumps around and in the network tab I see things taking tens of seconds to load.
(Google Chrome 93.0.4577.63 on macOS 11.5.1)

**Comment by kmosher** [comment]
FWIW, I think performance has managed to get even worse.

I was able to read these docs a couple weeks ago, but now trying to visit this page actually crashes my Chrome tab.

**Comment by alexandr-x-ursul** [comment]
The page is still broken more than a year later :(
If anyone stumbles across this issue, I recommend checking out the terraform doc for wafv2 webacl, a lot of info can be inferred from there.

**Comment by susanev** [comment]
another [internal discussion](https://pulumi.slack.com/archives/CK21FUGUA/p1671463582257799)

**Comment by aureq** [comment]
another inquiry via [HubSpot](https://api-na1.hubapi.com/notification-station/general/v1/notifications/cta/e2ca8a1f-3f8d-3ce4-9146-d726c4a25574?notificationPortalId=4429525&deliveryMethod=EMAIL)

**Comment by justinvp** [comment]
It's been mentioned internally by a couple folks, but we should consider working around this in docsgen, only emitting N nested types (possibly with a note that resource inputs have a lot of associated types and that some are not included). It should be a relatively cheap change in [`genNestedTypes`](https://github.com/pulumi/pulumi/blob/486b364e9088d6c59624111d081cd48ceed6f318/pkg/codegen/docs/gen.go#L980) or [`getTypes`](https://github.com/pulumi/pulumi/blob/486b364e9088d6c59624111d081cd48ceed6f318/pkg/codegen/docs/gen.go#L1711).

**Comment by lukehoban** [comment]
Fixed in https://github.com/pulumi/docs/pull/8552.

**Comment by susanev** [comment]
We have addressed this by only displaying the first 200 nested types. The page will now load. We will return to this when time allows us to develop a strategy that allows you to access the rest of the types.
