### ISSUE TITLE
Python type name inconsistency in documentation when used as an input

### ISSUE THREAD

**Issue by xiongchiamiov** [pulumi/registry#1524]
### What happened?

While creating an ECS Task Definition, the container definition class has two different names on the page and that makes it confusing as to which one to actually use.

### Steps to reproduce

On https://www.pulumi.com/registry/packages/aws-native/api-docs/ecs/taskdefinition/#container_definitions_python we see `TaskDefinitionContainerDefinitionArgs`:

![image](https://user-images.githubusercontent.com/23369/191354134-c4c3c8c7-ecd5-4234-8942-97fd92477676.png)

When you click that and go to https://www.pulumi.com/registry/packages/aws-native/api-docs/ecs/taskdefinition/#taskdefinitioncontainerdefinition , that gives us the name `TaskDefinitionContainerDefinition` (without "Args"):

![image](https://user-images.githubusercontent.com/23369/191354261-d123248c-8f68-4022-aabb-8ab700c094ff.png)

It appears that `TaskDefinitionContainerDefinitionArgs` is the name that works in code.

### Expected Behavior

Everything should use `TaskDefinitionContainerDefinitionArgs`.

### Actual Behavior

There are instances of `TaskDefinitionContainerDefinition` on the page.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
The changes for this have been merged; docs should be updated today. Thanks again for reporting this!
