### ISSUE TITLE
Redirect TODOs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#161]
A running list as I spot-check redirects:

- [x] https://www-reg-staging.pulumi-dev.io/docs/tutorials/ should redirect to /registry
- [ ] https://www-reg-staging.pulumi-dev.io/docs/tutorials/azure/azure-cs-functions/ should redirect to `azure-native`
- [ ]

**Comment by susanev** [comment]
@cnunciato is this still a thing that needs work done to complete?

**Comment by cnunciato** [comment]
Nope, we aren't doing anything more here -- we can close.
