### ISSUE TITLE
Missing aws.lambda.CallbackFunction from API reference

### ISSUE THREAD

**Issue by iulspop** [pulumi/registry#1614]
Hello :)

The [function serialization feature page](https://www.pulumi.com/docs/intro/concepts/function-serialization/#determining-the-required-node_modules-packages) references a Lambda ressource `new aws.lambda.CallbackFunction`, but the `CallbackFunction` resource isn't found in the [API reference under resources](https://www.pulumi.com/registry/packages/aws/api-docs/lambda/#resources). Am I looking in the wrong place?

File: [themes/default/content/registry/packages/aws/api-docs/lambda/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/lambda/)

**Comment by danielrbradley** [comment]
Yes, you're correct it's missing in the documentation right now due to it being a nodejs-specific feature and not available in other languages. 

We're tracking this via this existing issue https://github.com/pulumi/pulumi-aws/issues/2035. Feel free to add a 👍  reaction to upvote the issue
