### ISSUE TITLE
YAML function examples need to be updated for new syntax

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#1645]
Looks like we're still showing the uppercase property names (e.g., `Fn::Invoke` -- should be [`fn::invoke`](https://www.pulumi.com/docs/reference/yaml/#fninvoke), etc.):

![image](https://user-images.githubusercontent.com/274700/198744778-f163a681-982d-46ef-a644-71ea7998b3cd.png)

**Comment by lukehoban** [comment]
This has been fixed.  https://www.pulumi.com/registry/packages/azure-native/api-docs/network/getpublicipaddress/
