### ISSUE TITLE
How to update the listed version?

### ISSUE THREAD

**Issue by theogravity** [pulumi/registry#1646]
File: [themes/default/content/registry/packages/fusionauth/_index.md](https://www.pulumi.com/registry/packages/fusionauth/)

I've published updates since then but this page seems to be stuck on 0.9.7

**Comment by burak-upstash** [comment]
Similar problem here. I see that you guys have gh action checking for updates on community packages but they seem to skip as if no update is done... Should we do something about this or is this an internal thing?
Much thanks :)

**Comment by susanev** [comment]
@theogravity have you done a new release?

**Comment by theogravity** [comment]
I have

**Comment by theogravity** [comment]
looks like it's been updated now, so closing

**Comment by burak-upstash** [comment]
@susanev If you manually added theogravity's provider, could you also please have a look at this provider? https://github.com/upstash/upstash-pulumi-provider

**Comment by ringods** [comment]
@burak-upstash I found the culprit. Your Git repository is the only one in the package list which doesn't follow a standard naming pattern of `pulumi-<providername>`. In the Github Actions workflow, we match against a regex:

https://github.com/pulumi/registry/blob/90bdfc8adb29551d88ffd5075544d09433483cce/.github/workflows/generate-package-metadata.yml#L38-L43

and expect that the second part is the provider name:

https://github.com/pulumi/registry/blob/90bdfc8adb29551d88ffd5075544d09433483cce/.github/workflows/generate-package-metadata.yml#L45

During the run, you can see that your repository isn't even checked out:

https://github.com/pulumi/registry/actions/runs/3407835703/jobs/5667858743

The easiest way to have this fixed is by renaming your repository. Is it possible to rename:

`https://github.com/upstash/upstash-pulumi-provider`

to

`https://github.com/upstash/pulumi-upstash`

Then send a PR in this repo to update your listing:

https://github.com/pulumi/registry/blob/90bdfc8adb29551d88ffd5075544d09433483cce/community-packages/package-list.json#L75-L78

**Comment by lukehoban** [comment]
The original issue was resolved here - so I'll close this out.  

The commend from @ringods should likely be opened as an issue at https://github.com/upstash/upstash-pulumi-provider where the change would need to be made.
