### ISSUE TITLE
import sections often have incorrect formatting

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#1649]
Example here: https://www.pulumi.com/registry/packages/datadog/api-docs/aws/integration/

Happens on multiple pages under the "import" heading, should be in a `<p>` tag

<img width="1404" alt="Screen Shot 2022-10-28 at 5 09 49 PM" src="https://user-images.githubusercontent.com/97129308/199038417-f3fea2fe-3b22-4ec3-8b77-33673216398d.png">

**Comment by sean1588** [comment]
also related to the formatting (I think some of the content may be wrong as well):
![image](https://github.com/pulumi/registry/assets/16751381/21f3e882-dafb-4c45-99f5-c216e265b016)

https://www.pulumi.com/registry/packages/aws/api-docs/ec2/vpc/

**Comment by toriancrane** [comment]
Closing as these errors no longer seem to be present on the indicated pages.
