### ISSUE TITLE
dropped docstrings in api docs

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#1650]
(we can close this if it's redundant, but i couldn't find an open issue)

Example: https://www.pulumi.com/registry/packages/datadog/api-docs/dashboard/

i noticed we're dropping a ton of docstrings here -- makes this page feel very empty and unusable.

**Comment by cnunciato** [comment]
@anita-trimbur It looks like this may have been corrected since you originally posted it, so I'll close for now -- but feel free to reopen if necessary!
