### ISSUE TITLE
ensure all registry packages have logos

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#1654]
as part of style changes to the registry browse page, we need to ensure all packages have associated logos

- [x] aws quickstart aurora postgres
- [x] azure quickstart acr geo replication
- [x] cloud-init
- [x] gcp global cloudrun
- [x] random
- [x] tls
- [x] tls-self-signed-cert

**Comment by susanev** [comment]
@anita-trimbur lets leave this open as there may be new packages added without logos before we do the marketing launch of these changes.

**Comment by susanev** [comment]
calling this complete, theres one logo missing, but its out of our control.
