### ISSUE TITLE
Broken AWS Cloudfront Distribution example

### ISSUE THREAD

**Issue by TapTap21** [pulumi/registry#1686]
File: [themes/default/content/registry/packages/aws/api-docs/cloudfront/distribution/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/cloudfront/distribution/)

The `originAccessControlId` is assigned to something that doesn't exist or make sense in the context of the doc

**Comment by thomas11** [comment]
Thanks for the bug report, @TapTap21! We'll queue this up for fixing.

In the [original TF example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution), the expression is

```
origin_access_control_id = aws_cloudfront_origin_access_control.default.id
```

where [aws_cloudfront_origin_access_control](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_origin_access_control) is the name of another resource. It seems that we don't understand the `.default` part.

**Comment by viveklak** [comment]
I understand that `aws_cloudfront_origin_access_control.default.id` refers to a TF resource called `default`. Looks like the example is missing a definition for this. i.e. the source TF example is buggy.

**Comment by TapTap21** [comment]
A working example would look something like this:


    export const exampleCloudfrontOriginAccessControl =  
	  new aws.cloudfront.OriginAccessControl(  
	    "exampleCloudfrontOriginAccessControl",{  
	      originAccessControlOriginType: "s3",  
		  signingBehavior: "always",  
		  signingProtocol: "sigv4",  
	  },  
		  { provider: devAccountProvider }
	);
		  
And the origin block in the distrobution like this:

    origins: [  
	  {  
		  domainName: exampleBucket.bucketRegionalDomainName,  
		  originAccessControlId: exampleCloudfrontOriginAccessControl.id,  
		  originId: "originId1",  
	  },  
	],

So the missing part is the explicit definition of cloudfront.OriginAccessControl

**Comment by thomas11** [comment]
Thanks for your input, @viveklak. Since the upstream example is buggy, I don't think we'll fix this. The issue I linked might hopefully bring more clarity on these cases, maybe an annotation of these examples in the registry.
