### ISSUE TITLE
Documentation for TargetGroupHealthCheckArgs in awsx not available

### ISSUE THREAD

**Issue by aaronkao** [pulumi/registry#1689]
File: [themes/default/content/registry/packages/awsx/api-docs/lb/applicationloadbalancer/_index.md](https://www.pulumi.com/registry/packages/awsx/api-docs/lb/applicationloadbalancer/)

AWSX LB documentation is missing for [TargetGroupHealthCheckArgs](https://www.pulumi.com/registry/packages/awsx/api-docs/lb/applicationloadbalancer/#targetgrouphealthcheck)

**Comment by lukehoban** [comment]
Same issue as tracked in https://github.com/pulumi/registry/issues/210.
