### ISSUE TITLE
Change H1s in the API docs to match title tag

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#1702]
## overview

we would like to change the primary h1s in the API docs to correspond with the title tag that displays in browser. this is useful for both accessibility and seo. 

## example

[this resource in the datadog api docs ](https://www.pulumi.com/registry/packages/datadog/api-docs/aws/integration/) has two h1s on the page. the first appears in the header reads `Datadog`, referring to the name of the package. the second h1 appears in the content area for the api docs and reads `Integration`, referring to the particular resource. 

instead, we want only a single h1 on this page that appears inside the content area that matches the title tag for this page: `datadog.aws.Integration`.

## designs

_the api docs nav pictured in this frame is **not** included in this body of work_

<img width="1728" alt="1536+ (2)" src="https://user-images.githubusercontent.com/97129308/202806403-ad389aba-c325-4824-92b1-f2edc497f24e.png">

**Comment by susanev** [comment]
@anita-trimbur can you add a lil note on this one in the description, that the nav in the picture is not being implemented as part of this work?
