### ISSUE TITLE
align names on browse and package pages

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#1744]
**edit for clarity**: we want the names on the browse page, and the names of the detail pages pulling from the same data set. preference to pull from whatever the package detail pages are pulling from right now because those are often more detailed. we can come in later and clean up other issues in the packages themselves as needed. - @susanev 

-----

there are a few instances where an abbreviated name is used on the registry browse page that is different from the name used on the package page. see awsx as an example:

<img width="500" alt="Screen Shot 2022-11-30 at 11 46 57 AM" src="https://user-images.githubusercontent.com/97129308/204858301-f3b8407e-1b6d-4b55-9f40-82c047f27dac.png">
<img width="500" alt="Screen Shot 2022-11-30 at 11 47 03 AM" src="https://user-images.githubusercontent.com/97129308/204858299-33eddb9e-97ce-446e-a8dd-0eeabca4218a.png">

we would like all instances to use the more descriptive name.

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur The data for the browse page cards and the index pages comes from two different sources, so it looks like divergence comes from when one source is hand-updated, and the other is not updated to match.  I'll do an audit and put up a PR to align everything, but there's unfortunately not an easy answer that I can see that keeps them aligned going forward other than being vigilant on PRs where title attributes change.  

That said, I think this should be relatively rare + it's easy enough to fix.

**Comment by kimberleyamackenzie** [comment]
Eek, much more common than I guessed above 😬 - here's an audit of what's on browse vs index when they differ.  Let me know which we should go with.  I will also reach out on Slack about how we can make these two names converge bc this is obviously very common, so would be ideal to come from the same source.

- [ ] Google Cloud Classic (browse), Google Cloud (GCP) Classic (index)
- [ ] AWSx (browse), AWSx (Pulumi Crosswalk for AWS) (index)
- [ ] Azure Active Directory (browse), AzureAD (index)
- [ ] Azure Quickstart ACR Geo Replication (browse), Azure Quickstart ACR Geo Replicated (index)
- [ ] azure-justrun (browse), Azure Justrun (index)
- [ ] Command (browse), Command (preview) (index)
- [ ] Consul (browse), HashiCorp Consul (index)
- [ ] ec (browse), ElasticCloud (EC) (index)
- [ ] eventstorecloud (browse), Event Store Cloud (index)
- [ ] Google Cloud Native (browse), Google Native (index)
- [ ] HashiCorp Cloud Platform (HCP) (browse), HCP (index)
- [ ] Kubernetes Cert Manager (browse), cert-manager (index)
- [ ] Metabase (AWS) (browse), Metabase (index)
- [ ] Nomad (browse), HashiCorp Nomad (index)
- [ ] Proxmox VE (browse), Proxmox Virtual Environment (Proxmox VE) (index)
- [ ] Rancher 2 (browse), Rancher2 (index)
- [ ] Rancher RKE (browse), Rancher Kubernetes Engine (index)
- [ ] Sumo Logic (browse), SumoLogic (index)
- [ ] tls-self-signed-cert (browse), Self Signed Certificate (index)
- [ ] Vault (browse), HashiCorp Vault (index)

### Casing  diffs
- [ ] artifactory (browse), Artifactory (index) 
- [ ] astra (browse), Astra (index)
- [ ] checkly (browse), Checkly (index)
- [ ] flux (browse), Flux (index)
- [ ] heroku (browse), Heroku (index)
- [ ] OVH (browse), Ovh (index)
- [ ] MinIO (browse), Minio (index)
- [ ] random (browse), Random (index)
- [ ] tailscale (browse), Tailscale (index) 


Something going on with confluent + confluent cloud packages - one is labeled Confluent on browse, but titled confluent cloud on index and located at /confluentcloud, the one labeled Confluent Cloud on browse is also labeled Confluent Cloud on index but located at /confluent.

**Comment by susanev** [comment]
id like to "fix" this by using the same data source we use on the package detail pages on the package browse page. that's the change id like to happen in the issue. i don't want us to change anything about the casing in this issue, take it exactly as its coming in and then we can fix casing issues in the packages themselves later if needed.

for improvements beyond that, id like us to open a new tracking issue, because it will mean updating individual packages.

**Comment by susanev** [comment]
will explain more about confluent in team meeting tomorrow, don't want to talk about it more here since its a public issue.

**Comment by kimberleyamackenzie** [comment]
@susanev I don't believe we have a straightforward way to automatically align the two names (the name shown in the browse view, and the name shown on the Overview index page).  Here's my understanding of the pipeline (def gonna repeat things you already know, but typing it all out for clarity):

1) The repo of the provider has (among other things) two separate files in it that are relevant here - `schema.json` and `docs/_index.md`.  These two files are authored separately, however the maintainer of the provider sees fit.
2) A PR is made to add that provider to the Registry, via adding to [this file](https://github.com/pulumi/registry/blob/master/community-packages/package-list.json).  That includes a url to their `schema.json`.
3) Once that PR is merged, [this automated job](https://github.com/pulumi/registry/actions/workflows/generate-package-metadata.yml) creates a `providerName.yaml` file from the `schema.json`, and pulls the `docs/_index.md` file directly from the provider repo.
4) The name we show in the browse page comes from the `providerName.yaml` file, and the name we show on the index page comes directly from the frontmatter in that `docs/_index.md` file.  

So, as far as I understand it, it's at the discretion of the provider author/maintainer to keep those two names in sync.  I think we could be clearer about that intention in the docs.  I would guess that it's also possible for the automated job that adds the yaml file and the index file to the Registry repo to do some magic and change the title on the index file to match whatever is in the yaml file, but I am not sure how complicated that would be - it's a bit outside my wheelhouse.

Does that sound right, is there any part of the flow I'm misunderstanding?  What do you think re next steps?

**Comment by susanev** [comment]
@kimberleyamackenzie got it thx, ill take on this issue. ill fix the biggest offenders today, and will slowly work towards fixing the rest.

**Comment by susanev** [comment]
these need their install+config titles fixed

- [ ] aquasec
- [ ] astra
- [ ] aviatrix
- [ ] buildkite
- [ ] checkly
- [ ] doppler
- [ ] dynaatrace
- [ ] exoscale
- [ ] flux
- [ ] fusion auth
- [ ] gandi
- [ ] grafana
- [ ] harness
- [ ] hcp
- [ ] heroku
- [ ] koyeb
- [ ] launch darkly
- [ ] ovhcloud
- [ ] proxmoxve
- [ ] rootly
- [ ] scaleway
- [ ] sentry
- [ ] symbiosis
- [ ] time
- [ ] unifi
- [ ] upstash

**Comment by susanev** [comment]
alright i have open prs for everything except for rancher2 because i have an outstanding question about it; the tricky part now is going to be convincing everyone to do releases

**Comment by marns93** [comment]
@susanev I've created a new release for Heroku provider. (https://github.com/pulumiverse/pulumi-heroku/actions/runs/3618262104/jobs/6098043475)

**Comment by susanev** [comment]
im calling this done from my perspective, stuff will slowly roll in, and that's okay!
