### ISSUE TITLE
registry ux papercuts

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#1754]
### browse page
- [x] change card headers from `font-weight: 700;` to `font-weight: 600;`
- [x] leave empty space underneath filters so content doesn't jump down when chips appear; should be about 50px of space needed
- [x] adjust max-height of the empty package placeholder 

### package navigation
- [x] change text-color for inactive menu navigation tabs to align with inactive language selectors `#5f6065`
- [x] package navigation tabs should not span content area

### other
- [x] add alt text to all logos: `"<package name> logo"`

**Comment by susanev** [comment]
@anita-trimbur @kimberleyamackenzie i added alt text for the package logos to the list

**Comment by kimberleyamackenzie** [comment]
I'm not sure what we mean by `package navigation tabs should not span content area`, otherwise the remainder of this is in PR at https://github.com/pulumi/registry/pull/1791.
