### ISSUE TITLE
Examples for New Relic Workflow resource fail to render properly

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#1804]
Missing chooser controls, reported by a friend from New Relic:

https://www.pulumi.com/registry/packages/newrelic/api-docs/workflow/

![image](https://user-images.githubusercontent.com/274700/206544645-f8e77380-eb1d-41f3-ad37-9c6e0aec7dc6.png)

**Comment by susanev** [comment]
this is tracked in https://github.com/pulumi/registry/issues/1401
