### ISSUE TITLE
The examples shown on https://www.pulumi.com/registry/packages/aiven/ are no longer valid.

### ISSUE THREAD

**Issue by dewan-ahmed** [pulumi/registry#1806]
### What happened?

The examples shown on https://www.pulumi.com/registry/packages/aiven/ are no longer valid as the https://registry.terraform.io/providers/aiven/aiven/latest/docs no longer uses generic `aiven.service` type. There has been some other changes as well in the v3 of the Aiven Terraform Provider from v2.

Please update the examples to reflect the latest resource definitions. 

### Steps to reproduce

1. Navigate to https://www.pulumi.com/registry/packages/aiven/
2. Try to create an Aiven resource using any of the examples shown on the page

### Expected Behavior

Aiven resources will be created.

### Actual Behavior

Error mentioning that the resource definition is invalid.

### Additional context

https://pulumi-community.slack.com/archives/CB81H6DG9/p1670530930257399?thread_ts=1670519388.908169&cid=CB81H6DG9

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
thx @dewan-ahmed for reporting the issue! we will fix it up as soon as time allows.

we also welcome prs if you'd like to submit one. hope you have a great week!
https://github.com/pulumi/registry/edit/master/themes/default/content/registry/packages/aiven/_index.md

**Comment by dewan-ahmed** [comment]
Thanks @susanev 

I raised https://github.com/pulumi/templates/pull/479 and https://github.com/pulumi/templates/pull/480 for the template repo. Based on the review feedback on those PRs, I can certainly create a PR against https://github.com/pulumi/registry/edit/master/themes/default/content/registry/packages/aiven/_index.md to update the examples.

**Comment by iwahbe** [comment]
This has been fixed by the roll-out of generated `_index.md` docs.
