### ISSUE TITLE
links without anchor text

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#1819]
okay i figured out what is causing the large number of seo errors about no anchor text
its the link to the github repo in the package details
i _think_ if we drop the `https://` from the anchor text (but leave the href as is)
or it may be even better to make the anchor text `<package name> repository`
then this will be fixed

<img width="826" alt="Screen Shot 2022-12-09 at 8 20 23 PM" src="https://user-images.githubusercontent.com/5489125/206828782-16d93c54-746c-4ee1-9fd0-e2514d4e7edf.png">

this causes 5,038 errors

because this is at the bottom of every api docs reference page

**Comment by susanev** [comment]
@kimberleyamackenzie or @sean1588 either of you up for fixing this?

**Comment by susanev** [comment]
heres the line i think we need to edit
https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/templates/package_details.tmpl#L5

**Comment by sean1588** [comment]
changes are now live as of: https://github.com/pulumi/docs/pull/8480
