### ISSUE TITLE
update how-to guide headings to use page title

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#1823]
seo doesnt like different pages having the same h1
and since we have the same how-to guide in multiple languages on different pages this leads to issues

the titles are customized to include an or bar and the language (see breadcrumb link), lets update the h1s to use the same thing

<img width="727" alt="Screen Shot 2022-12-10 at 12 00 47 PM" src="https://user-images.githubusercontent.com/5489125/206873249-7e67724f-b30e-4ccc-ba67-d98d1986c824.png">

**Comment by susanev** [comment]
@sean1588 after your current pr lands, up for taking this?

**Comment by sean1588** [comment]
@susanev yeah I can take a look at this.
