### ISSUE TITLE
add deprecation message into the confluent cloud package card

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#1828]
## overview
we'd like to add a message into the new package page card for the confluent cloud provider to better communicate that the package has been deprecated.

## designs
- instead of the info icon, uses a warning icon in our warning color `#BD4C85`
- warning icon also appears on the collapsed card to the left of the publication date, size 14x14
- [fontawesome equivalent](https://fontawesome.com/icons/triangle-exclamation?s=solid&f=classic) of the warning icon, `triangle-exclamation`

<img width="300" alt="Group 559 (1)" src="https://user-images.githubusercontent.com/97129308/207133910-abbb4960-a712-466b-9d62-ba607b20a7ee.png">
<img width="300" alt="Frame 775 (1)" src="https://user-images.githubusercontent.com/97129308/207133920-17bbc2b0-1e46-4e1f-ae69-5463a874c509.png">

**Comment by anita-trimbur** [comment]
@susanev let me know if this is the right direction for the text, we can adjust this in whatever way you think best

**Comment by susanev** [comment]
whoa that was fast, and i love this!

is that white accessible on the orange?

**Comment by anita-trimbur** [comment]
i can double check, but i think jonelle ran this thru a contrast checker before she updated the design system

**Comment by anita-trimbur** [comment]
it passes for graphical components but not text. if we're wanting it to pass for text, we would have to bump the base color up from this one (orange600) to orange800 `#B35F16`.

**Comment by susanev** [comment]
@anita-trimbur yah you can go with the pink if you'd like, you can also use dark text instead of white and keep the orange you have. whatever you think is b est.

**Comment by susanev** [comment]
this is mostly done, just needs the warning icon instead of the info icon
