### ISSUE TITLE
responsive & style adjustments to package pages

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#1830]
follow-on adjustments to the registry

### highest priority

- [x] #1847 PR: https://github.com/pulumi/registry/pull/1848
- [x] https://github.com/pulumi/registry/issues/1823 PR: https://github.com/pulumi/registry/pull/1849
- [x]  https://github.com/pulumi/registry/issues/1829 PR: https://github.com/pulumi/theme/pull/407
<img width="700" alt="Screen Shot 2022-12-13 at 6 27 16 AM" src="https://user-images.githubusercontent.com/97129308/207382008-e21d3d41-942d-4844-910a-9c1cc71aa707.png">

- [x] #1881
<img width="700" alt="api-nav-sad-width" src="https://user-images.githubusercontent.com/97129308/209007553-b16bf5b0-0744-48fa-8f74-6b9e8d482bb7.png">

### mid priority

- [ ] fix how to guide sub pages that have a jump from h1 to h3 headings. the h3 tags should be switched to h2.
- [x] https://github.com/pulumi/registry/issues/1824
- [ ] address content width issues on how-to guide sub pages
- [ ] reduce space between breadcrumbs and nav
- [ ] reduce space between nav and h1s

### low priority

- [ ] under the 1280 breakpoint, prevent the collapsed card from jumping around between tabs
<img width="700" alt="Screen Shot 2022-12-12 at 4 07 10 PM" src="https://user-images.githubusercontent.com/97129308/207154929-511b9ee3-a88b-4ae6-82cd-aaded633ea16.png">
<img width="700" alt="Screen Shot 2022-12-12 at 4 07 02 PM" src="https://user-images.githubusercontent.com/97129308/207154931-5d6e40ae-2407-4283-abf4-553d5ce8353b.png">

- [ ] similar behavior under 1024 but most noticeably on the how-to-guides
- [ ] remove breadcrumbs on mobile screen widths
- [ ] center the page content below the 1280 breakpoint

**Comment by susanev** [comment]
@anita-trimbur reminder to get issues opened for each of the items in the checklist

**Comment by anita-trimbur** [comment]
ah my bad, this got lost in the fold. i'll get those open today!
