### ISSUE TITLE
Possible typo in https://www.pulumi.com/registry/packages/pulumiservice/

### ISSUE THREAD

**Issue by bennettp123** [pulumi/registry#1873]
### What happened?

Bad link at https://www.pulumi.com/registry/packages/pulumiservice/

### Steps to reproduce

1. Browse to https://www.pulumi.com/registry/packages/pulumiservice/
2. Click the "Pulumi Service" link (pictured below)

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1610227/209654632-949e8778-6a07-4af2-93ca-cab0607ea662.png">

### Expected Behavior

The target link tells me about the pulumi service

### Actual Behavior

The target link tells me about a cloud provider called scaleway? https://www.scaleway.com/

### Output of `pulumi about`

not applicable

### Additional context

Seems like the link is defined here: https://github.com/pulumi/registry/blob/ac89073f60227f0e6a1eba26bd21657ec3bec0e4/themes/default/content/registry/packages/pulumiservice/_index.md?plain=1#L7

There's a similar link in the scaleway provider docs: https://github.com/pulumi/registry/blob/ac89073f60227f0e6a1eba26bd21657ec3bec0e4/themes/default/content/registry/packages/scaleway/_index.md?plain=1#L7

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
oh yikes, will fix, thx for reporting!
