### ISSUE TITLE
Wrong Variable name

### ISSUE THREAD

**Issue by dasasathyan** [pulumi/registry#1875]
File: [themes/default/content/registry/packages/confluentcloud/installation-configuration.md](https://www.pulumi.com/registry/packages/confluentcloud/installation-configuration/)

The Cloud API Secret has a typo with the name. It has to be `confluentcloud:cloudApiSecret`  not `confluentcloud:clouaApiSecret`

**Comment by susanev** [comment]
hi @dasasathyan thx for the report! would you be up for opening up a pr with the fix?

https://github.com/pulumi/registry/edit/master/themes/default/content/registry/packages/confluentcloud/installation-configuration.md

**Comment by dasasathyan** [comment]
Hi @susanev Here is it: https://github.com/pulumi/registry/pull/1877
