### ISSUE TITLE
Azure Native version guide layout is incorrect

### ISSUE THREAD

**Issue by praneetloke** [pulumi/registry#197]

**Comment by kimberleyamackenzie** [comment]
Talked with @susanev about how to handle this:

- [ ] You get to this page by going to the overview, and in a description towards the bottom, there's a link to this version guide
- [ ] We want to handle like we do with how to guides - clicking the `version guide` link brings you to this page, and it's layout/styling is like you're on the overview (so overview tab is underlined, etc)
- [ ] There's a breadcrumb that shows how you got here (so Azure Native > Version Guide)
