### ISSUE TITLE
interacting with the tabs on a package page should not send you to the top of the page

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#200]
## overview
similar to https://github.com/pulumi/registry/issues/130 when interacting with the tabs (overview, install+config, API docs, guides) on a package page, your position on the page should not change and the tabs should stay in view. this is especially important on smaller screens.

**Comment by kimberleyamackenzie** [comment]
Putting a size/M label on this, the same as #130 - but I think both items together are a M, not individually.  One solution should be able to be applied to both areas with minimal additional effort.
