### ISSUE TITLE
Provider Pulumi-ZIA Logo URL Request

### ISSUE THREAD

**Issue by willguibr** [pulumi/registry#2003]
I need to add the Zscaler Logo to the registry.
When using the attribute LogoURL it makes the CI/CD fail. The CI/CD only works when removing the LogoURL completely.
`LogoURL:                 "https://www.zscaler.com/themes/custom/zscaler/logo.svg",`
File: [themes/default/content/registry/packages/zia/_index.md](https://www.pulumi.com/registry/packages/zia/)

**Comment by susanev** [comment]
we can add this logo for you, whats the cicd failure though? can i see the output?

**Comment by willguibr** [comment]
Hi @susanev 
This is the error it returns every time I add the logoURL attribute pointing to an image. The interesting part is that my second provider pulumi-zpa, has the logoURL pointing to a svg image and there is no problem during the CI.
<img width="914" alt="Screen Shot 2023-01-24 at 10 57 11 PM" src="https://user-images.githubusercontent.com/23208337/215812354-e23380a3-ab8d-4e4b-8bfd-6e74b5bbfde2.png">

**Comment by susanev** [comment]
im going to close is put, but pls reopen if i can help ya more, thank you!!
