### ISSUE TITLE
Whole card element of the provider clickable

### ISSUE THREAD

**Issue by dirien** [pulumi/registry#205]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be nice, if the whole card of the provider is clickable and not only the title and header.

![image](https://user-images.githubusercontent.com/38325136/137763736-4ce9ef80-6abe-4f7d-9285-280c2ebf2698.png)

### Affected area/feature

Pulumi registry

**Comment by EvanBoyle** [comment]
Thanks for the suggestion @dirien. We do have plans to make improvements here, but we will be taking a slightly different approach (making the filter tags interactive).
