### ISSUE TITLE
Comments from original documentation are ignored

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/registry#2106]
File: [themes/default/content/registry/packages/gcp/api-docs/cloudrunv2/job/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrunv2/job/)

In pulumi doc
https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrunv2/job/#cloudrunv2-job-secret
<img width="307" alt="image" src="https://user-images.githubusercontent.com/7480694/220078581-4769068c-2a59-4ab6-9958-85e021877857.png">

terraform doc
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_job#example-usage---cloudrunv2-job-secret

<img width="528" alt="image" src="https://user-images.githubusercontent.com/7480694/220078494-f878cd9b-e6f0-4588-bd38-965672fbf1c5.png">

**Comment by danielrbradley** [comment]
Hi @1oglop1 thanks for suggestion. Indeed this would be nice to have the documentation, unfortunately I think this would be very tricky to implement as out language parsers and ASTs don't currently support comments - they're ignored. If you look at [the documentation for these properties](https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrunv2/job/#defaultmode_nodejs) these octal values are explained in good detail. Therefore, I'm going to close this as "won't fix", though could re-open if anyone can recommend a simple enough approach to implement this.
