### ISSUE TITLE
API modules aren't sorted for Kubernetes

### ISSUE THREAD

**Issue by joeduffy** [pulumi/registry#211]
The API modules for Kubernetes seem to be in a random order. At a glance, other providers seem to be fine (and I haven't found another example of this), so I wonder if this is just a problem with Kubernetes.

![image](https://user-images.githubusercontent.com/3953235/137790456-b8d19a34-8253-47f2-9f3f-aef57a31f591.png)

**Comment by praneetloke** [comment]
Note that while the fix is merged, as we regenerate API docs for providers with each provider version release the issue will correct itself since we would regenerate the JSON for the tree at the same time as well.
