### ISSUE TITLE
`set-output` in Github Action workflows deprecated by 31 May 2023

### ISSUE THREAD

**Issue by ringods** [pulumi/registry#2121]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`set-output` in Github Action workflows will be fully deprecated by 31 May 2023.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Affected area/feature

The workflow file `.github/workflows/generate-package-metadata.yml` is using `set-output`.

**Comment by susanev** [comment]
@sean1588 is this fixed now? can we close this?

**Comment by sean1588** [comment]
i think this should be good now. If anyone happens to come across more of these set-output warnings  please let me know.

https://github.com/pulumi/registry/pull/2577
https://github.com/pulumi/registry/pull/2539
https://github.com/pulumi/registry/pull/2538
https://github.com/pulumi/registry/pull/2509
https://github.com/pulumi/pulumi-hugo/pull/2936
https://github.com/pulumi/pulumi-hugo/pull/2903
