### ISSUE TITLE
Allow filtering using the package tags on the registry index page

### ISSUE THREAD

**Issue by praneetloke** [pulumi/registry#213]
* [ ] On hover/focus, the card filters should use the colors defined in this [figma frame](https://www.figma.com/file/SnQTIMgxBLMXO8tbh5LrnC/registry-detailed-design-info?node-id=1%3A277) this is so we have a difference between hover/focus and selected.
* [ ] It should be possible to tab to the filters and fully interact with them with your keyboard

**Comment by susanev** [comment]
these were removed entirely so closing
