### ISSUE TITLE
[Epic] Single-repository Pulumi Packages

### ISSUE THREAD

**Issue by infin8x** [pulumi/registry#222]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Epic details

Today, a Pulumi Package's contents are spread across a few places (see list below). To make it easier for anyone in the Pulumi Community to author a package and prepare for #206, we should update our publishing processes to source all of that content from the package's repository. We should then move the content for all of our existing packages into their repositories.

- The **code** and the **schema** are in the package's repository
- The **API documentation** (generated from the schema) is in https://github.com/pulumi/docs
- The **hand-written documentation** (Overview, Installation & Configuration) is in https://github.com/pulumi/registry
- The **how-to guides** are in https://github.com/pulumi/examples

## Work items

- [ ] Interested Parties 
- [ ] Quality plan 
- [ ] #223
- [ ] #224
- [ ] #221
- [ ] Update the Pulumi Packages publishing guide to match the changes made in this Epic
- [ ] Update any relevant Pulumi developer documentation to match the changes made in this Epic

## Launch readiness 🎁

[Link](link-to-release-tracker)

**Comment by susanev** [comment]
we are going a different direction with this, so closing.
