### ISSUE TITLE
Enable Overview, Installation & Configuration pages to be stored inside the repository

### ISSUE THREAD

**Issue by infin8x** [pulumi/registry#224]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Today, hand-authored Overview and Installation & Configuration pages for a Pulumi Package are stored in https://github.com/pulumi/registry. As part of #222 and in preparation for #206, we should:

- [x] Enable the package publish process to pull the Overview content directly from the package's README
- [ ] Ensure the boilerplate repositories provide a great README template such that the package will look great in Pulumi Registry
- [x] Enable the package publish process to pull the Installation & Configuration content from `docs/installation-configuration.md`
- [x] Update Pulumi Registry to hide the Installation & Configuration tab if `docs/installation-configuration.md` is blank

**Comment by iwahbe** [comment]
I have opened follow-up issues in each of our boilerplate repos.
