### ISSUE TITLE
fix pages with duplicate title tags

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#2285]
these negatively impact seo
i beleive the how-to guides is because they are literally copying the content to both places; can we hack the title in some way to indicate whether native or classic?

for almost everything else i think we need to figure out with the /api-docs and /api-docs/x have the same title

1.
https://www.pulumi.com/registry/packages/azure-native/how-to-guides/azure-py-aks-multicluster/
https://www.pulumi.com/registry/packages/azure/how-to-guides/classic-azure-py-aks-multicluster/

2.
https://www.pulumi.com/registry/packages/azure/how-to-guides/classic-azure-go-aks-multicluster/
https://www.pulumi.com/registry/packages/azure-native/how-to-guides/azure-go-aks-multicluster/

3.
https://www.pulumi.com/registry/packages/google-native/api-docs/batch/
https://www.pulumi.com/registry/packages/kubernetes/api-docs/batch/

4.
https://www.pulumi.com/registry/packages/metabase/api-docs/
https://www.pulumi.com/registry/packages/metabase/api-docs/metabase/

5.
https://www.pulumi.com/registry/packages/azure/how-to-guides/classic-azure-ts-aks-multicluster/
https://www.pulumi.com/registry/packages/azure-native/how-to-guides/azure-ts-aks-multicluster/

6.
https://www.pulumi.com/registry/packages/purrl/api-docs/
https://www.pulumi.com/registry/packages/purrl/api-docs/purrl/

7.
https://www.pulumi.com/registry/packages/aws/api-docs/iam/
https://www.pulumi.com/registry/packages/aws-iam/

8.
https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/restapi/
https://www.pulumi.com/registry/packages/aws-apigateway/api-docs/restapi/

9.
https://www.pulumi.com/registry/packages/aws/api-docs/iam/user/
https://www.pulumi.com/registry/packages/aws-iam/api-docs/user/

10.
https://www.pulumi.com/registry/packages/azure/how-to-guides/classic-azure-ts-aks-helm/
https://www.pulumi.com/registry/packages/azure-native/how-to-guides/azure-ts-aks-helm/

11.
https://www.pulumi.com/registry/packages/aws/api-docs/iam/policy/
https://www.pulumi.com/registry/packages/aws-iam/api-docs/policy/

12.
https://www.pulumi.com/registry/packages/kubernetes/api-docs/storage/
https://www.pulumi.com/registry/packages/google-native/api-docs/storage/

**Comment by tofuni** [comment]
Updated crawl for [duplicate title tags](https://docs.google.com/spreadsheets/d/1rDnCqCKNDWMPCc_QB67F0qqRcRCyLxaiPfIEqf2d9LY/edit#gid=0). 

@susanev - I have a few questions that I want to run by you during our call this Friday, but otherwise we can handle any pages in "Hugo Repo" and any how-to guides in "Registry" :)
