### ISSUE TITLE
fix duplicate meta descriptions

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#2286]
see [internal spreadsheet](https://docs.google.com/spreadsheets/d/1bGv3Gh2ngeys3Z_oV7uAABFCe6XcGbo1DsX0LDJYMWk/edit?usp=sharing) for more deets
we have 137 pages with duplicate meta descriptions
we need to investigate why and then fix them

**Comment by tofuni** [comment]
Updated crawl of [duplicate meta descriptions](https://docs.google.com/spreadsheets/d/1J1tWnshbxXo0EUEMLg3hNRrf83BPIqoV_ll_NGZNZbs/edit#gid=0).

@susanev - we've got the resolutions mapped out for these as well and can handle all of the Hugo repo pages, but will need to pass to your team to implement for the auto-generated registry and docs reference pkg pages.
