### ISSUE TITLE
Deprecate equinix-metal provider

### ISSUE THREAD

**Issue by mnlumi** [pulumi/registry#2294]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The equinix-metal provider is being replaced by the 'equinix' provider. The former needs to be marked as deprecated in the [registry](https://www.pulumi.com/registry/packages/equinix-metal/) and the [github repo](https://github.com/pulumi/pulumi-equinix-metal).

**Comment by ocobleseqx** [comment]
This issue is related to https://github.com/pulumi/registry/issues/262
