### ISSUE TITLE
Serve the Pulumi Schema directly from the Registry

### ISSUE THREAD

**Issue by lukehoban** [pulumi/registry#2388]
It would be really useful if the registry could serve the raw Pulumi Schema for each package (and ideally package version) from the public registry site.

Bonus if it could also serve individual schema types (to avoid needing to download massive schema files), though this is less critical.

**Comment by cnunciato** [comment]
Sounds like a fine addition, but curious how you think this would be practically useful @lukehoban. Can you share a few words here as to how you imagine this being used?

**Comment by lukehoban** [comment]
I think it’s okay to close this out. We’ve built up a ton of machinery for acquiring and processing schema outside of dependence on the registry, so this is no longer as important.
