### ISSUE TITLE
Registry docs headings missing interactive link icons

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/registry#239]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In the docs site, all the headings have a link that you can click on:

![image](https://user-images.githubusercontent.com/109047/138068191-3c0ce2de-ce3c-4692-a772-2d8393729311.png)

The registry doesn't have this (I know you can click on the contents on the right-hand side, but on a mobile device that involves scrolling down to get to it)

### Affected area/feature

Docs

**Comment by susanev** [comment]
yes, we should absolutely do this. im not sure at what point in the move they were lost.
i will say the ids are still there on the elements so you can still use anchor links as a workaround until we get this fixed.
e.g., https://www.pulumi.com/registry/packages/azure-native/#migration
