### ISSUE TITLE
Performance with Safari 15 is abysmal

### ISSUE THREAD

**Issue by nesl247** [pulumi/registry#240]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Performance using Safari is abysmal. From what I can tell, it's related to the loading of API Navigation. It works fine in chromium based browsers which makes me wonder if that is all that was tested.

### Steps to reproduce

1. Open any API Docs page in Safari 15

Expected: The page should not be slow.
Actual: The page is extremely slow and is unresponsive until API Navigation is fully loaded.

**Comment by cnunciato** [comment]
Note that as of today, we're running Lighthouse daily in CI, which includes analyzing these registry API Docs pages. https://github.com/pulumi/docs/actions/workflows/check-lighthouse.yml The results are  uploaded as GHA artifacts, so there should be some useful performance data being gathered already on this.

**Comment by EvanBoyle** [comment]
Took a trace in chrome, looks like 2 seconds of javascript running prior to rendering the tree. Network request is actually pretty quick for me atleast.

![Screen Shot 2021-10-20 at 10 11 39 AM](https://user-images.githubusercontent.com/2553171/138139916-6f5de9e5-e4fb-4574-ae20-d7c0b91d062c.png)

**Comment by EvanBoyle** [comment]
@nesl247 we deployed another fix. Would you mind taking another look and reopening the issue if it is still a problem?
