### ISSUE TITLE
pulumiverse time provider binary install instructions incorrect

### ISSUE THREAD

**Issue by justinvp** [pulumi/registry#2439]
For example: https://www.pulumi.com/registry/packages/time/installation-configuration/

<img width="804" alt="Screen Shot 2023-05-03 at 10 08 00 PM" src="https://user-images.githubusercontent.com/710598/236116766-90ace4d2-28f2-4016-ba5c-20de93c974e4.png">

Trying to run `pulumi plugin install resource time v0.1.7` doesn't work for 2 reasons:

1. This plugin is hosted at a 3rd party URL, so it requires the `--server` flag:

    ```
    pulumi plugin install resource time v0.1.7 --server github://api.github.com/pulumiverse/pulumi-time
    ```

2. The above doesn't work, though, because there is no `v0.1.7` version. (See https://github.com/pulumiverse/pulumi-time/releases). The latest release is [v0.0.13](https://github.com/pulumiverse/pulumi-time/releases/tag/v0.0.13).

## Suggestions

- The `--server` flag is required for any schema that specifies a plugin download URL and this should be reflected in the registry docs.
- Either the latest version should be shown:

    ```
    pulumi plugin install resource time v0.0.13 --server github://api.github.com/pulumiverse/pulumi-time
    ```

    or, no version should be shown, in which case, if the URL is from GH, the CLI will determine and download the latest version:

    ```
    pulumi plugin install resource time --server github://api.github.com/pulumiverse/pulumi-time
    ```

**Comment by susanev** [comment]
@ringods do you have permissions to transfer this to the pulumiverse repo? also, can i get those permissions?

**Comment by ringods** [comment]
I duplicated the issue in the respective repo.

@justinvp can you next time file the issue in the upstream repo of the provider?

**Comment by ringods** [comment]
@susanev I couldn't transfer the issue either due to this:

> Note: You can only transfer issues between repositories owned by the same user or organization account. A private repository issue cannot be transferred to a public repository.

https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by justinvp** [comment]
> @justinvp can you next time file the issue in the upstream repo of the provider?

Ah, will do! I was under the impression that these docs were auto-generated and not manually maintained in the provider's repo.

**Comment by ringods** [comment]
For non-Pulumi maintained providers, the official sources are always in the provider repo. In `pulumi/registry` (this repo), there is a build step which copies the `docs` content over from the provider repo at every new release so it is included in the docs generation.

For (some of the) Pulumi maintained providers, the main docs indeed live here, but I'm not sure if we also have Pulumi maintained providers where we copy over from the provider repo. @susanev do you have a definite answer on this?
