### ISSUE TITLE
Breadcrumbs separator does not render on Firefox

### ISSUE THREAD

**Issue by praneetloke** [pulumi/registry#2555]
### What happened?

The separator used in breadcrumbs does not render in Firefox but it seems to render just fine on Chrome.

Firefox:
![image](https://github.com/pulumi/registry/assets/1466314/4bf20883-98cd-4203-af79-698c3243ed2d)

All other browsers (Chrome, Edge, Safari):
![Screenshot 2023-05-24 at 8 55 01 AM](https://github.com/pulumi/registry/assets/1466314/38734f2d-acf4-49fc-818a-dae08b98e018)

### Expected Behavior

The separator renders on all browsers.

### Steps to reproduce

Navigate to any resource and take note of the breadcrumb path at the top of the page on Firefox.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
oh no, thank you for the report!! will take a look.
