### ISSUE TITLE
Resource Icon not aligned with name

### ISSUE THREAD

**Issue by iwahbe** [pulumi/registry#2623]
### What happened?

Given the following registry page:
<img width="1792" alt="Screenshot 2023-06-05 at 10 29 42 AM" src="https://github.com/pulumi/registry/assets/22222529/31aea45d-0584-424f-93dc-8fad55fa76a3">

We see correct alignment of the  <img width="22" alt="Screenshot 2023-06-05 at 10 30 13 AM" src="https://github.com/pulumi/registry/assets/22222529/14e7bad4-d481-4571-8d67-b2f693aa53db"> icon in the left nav, but not when in a module page listing resources.

The resource + icon on the left nav looks like this:
<img width="173" alt="Screenshot 2023-06-05 at 10 32 15 AM" src="https://github.com/pulumi/registry/assets/22222529/908b8910-e423-4b4d-8353-791baa112a4a">

The module (main panel) equivalent of the same resource looks like this:
<img width="176" alt="Screenshot 2023-06-05 at 10 32 51 AM" src="https://github.com/pulumi/registry/assets/22222529/4348efce-bddc-4b32-a520-3de404b23203">

### Expected Behavior

All icons are aligned.

### Steps to reproduce

Go to https://www.pulumi.com/registry/packages/aws/api-docs/account/ on a MacBookPro with Safari Version 16.4 (18615.1.26.11.23).

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
https://github.com/pulumi/pulumi/pull/11985

**Comment by iwahbe** [comment]
Sounds good. What's stopping us from merging #11985?

**Comment by susanev** [comment]
idk time, ill do it today, sry!
