### ISSUE TITLE
Update Actions to use Node.js 16

### ISSUE THREAD

**Issue by jkodroff** [pulumi/registry#2625]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We have a lot of warnings in our Actions logs because we're using Actions that run on Node 12. We should update to Node 16. Example: https://github.com/pulumi/registry/actions/runs/5175759543

**Comment by cnunciato** [comment]
Closing via https://github.com/pulumi/registry/pull/3730.
