### ISSUE TITLE
Disable automerge on PRs that would break the build

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#2705]
We currently merge provider PRs automatically, but these PRs are often missing required documentation files, which breaks the publishing pipeline because these providers' pages can't be built. 

![image](https://github.com/pulumi/registry/assets/274700/64e0e8bc-5bad-49ee-8583-7e99abad840c)

We should disallow this.

**Comment by susanev** [comment]
only internal packages automerge not community packages

**Comment by cnunciato** [comment]
So we did add some validation to handle this, but we [commented it last week](https://github.com/pulumi/registry/pull/2797/files) in order to fix a problem with related to layout naming. So I'm adding this issue back in to cover adjusting what's commented to restore the check for the existence of docs (which we do need) but not fail on the bad-layout-name part.
