### ISSUE TITLE
AWS Classic release date displaying incorrectly

### ISSUE THREAD

**Issue by mnlumi** [pulumi/registry#2896]
### What happened?

On the [AWS Classic provider](https://www.pulumi.com/registry/packages/aws/) registry pages, the last release date is showing incorrectly. Currently displayed as Jan, 1 0001.

<img width="387" alt="Screenshot 2023-07-20 at 11 55 31 PM" src="https://github.com/pulumi/registry/assets/118926824/6743e55d-2ee6-4b1c-a353-35e6c212db15">

### Expected Behavior

I expect it to show the correct release date.

### Steps to reproduce

Navigate to https://www.pulumi.com/registry/packages/aws/ and look at the box in the top right hand corner.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
[This value](https://github.com/pulumi/registry/blob/53a66559c30cfd5f6b9fddd4f5b9ca2add1f4c87/themes/default/data/registry/packages/aws.yaml#L14) is incorrect -- it needs to be updated to align with the actual release date of this version (obtained from the [GitHub release page](https://github.com/pulumi/pulumi-aws/releases/tag/v5.42.0)):

```
> new Date("2023-07-11T11:04:45Z").getTime()
1689073485000
```

The correct value should be `1689073485`.
