### ISSUE TITLE
Supporting types missing for Typescript

### ISSUE THREAD

**Issue by mnlumi** [pulumi/registry#2966]
### What happened?

This page https://www.pulumi.com/registry/packages/azure-native/api-docs/insights/component/#supporting-types does not provide info for supporting types. 

![azure-components-supporting-types](https://github.com/pulumi/pulumi-azure-native/assets/118926824/3c648eca-7710-4c41-9255-b86b02fed790)

### Expected Behavior

I expect to see the supporting types information. 

Example: 

```

IngestionMode | Indicates the flow of the ingestion. | 'ApplicationInsights''ApplicationInsightsWithDiagnosticSettings''LogAnalytics'
```

From: https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/components?pivots=deployment-language-bicep#applicationinsightscomponentproperties

### Steps to reproduce

Visit the link listed above. See that there are no supporting types shown.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by sean1588** [comment]
just an observation - it looks like this happens for types that are listed as part of a union type.
