### ISSUE TITLE
api nav loading blocks interactions on other objects on the page

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/registry#303]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

At the moment, if you open a page in the registry ([for example](https://www.pulumi.com/registry/packages/azure-native/api-docs/apimanagement/)) you have to wait for the API Navigation on the left-hand side to load before you can click on anything on the page

### Steps to reproduce

1. Go to https://www.pulumi.com/registry/packages/azure-native/api-docs/apimanagement/
2. Whilst the nav tree on the left is loading, click on a link

It's probably more noticeable in the Azure Native provider docs

Expected:  Link is clickable straight away
Actual:  You have to wait for the API Navigation tree to load before you can click anything 

This is in Chrome on MacOS

**Comment by susanev** [comment]
related: https://github.com/pulumi/registry/issues/240 and https://github.com/pulumi/registry/issues/250
