### ISSUE TITLE
insufficient documentation to make use of import

### ISSUE THREAD

**Issue by buchs** [pulumi/registry#3039]
### Problem description

AWS APIGatewayv2 documentation - each resource, has insufficient import documentation. One can not tell what are the required identifiers. E.g. : https://www.pulumi.com/registry/packages/aws/api-docs/apigatewayv2/route/#import

### Affected product version(s)

https://www.pulumi.com/registry/packages/aws/api-docs/apigatewayv2/route/#import

### Suggestions for a fix

One needs to know what are the required identifiers.  This is not sufficient: aabbccddee/1122334

**Comment by interurban** [comment]
Thank you so much for submitting this issue @buchs we're looking into getting this fixed.

**Comment by cnunciato** [comment]
@buchs Thank you again for reporting this issue. To address some of the confusion here, I've added a link in the associated PR to the docs that explain how to find these identifiers on the page, but I agree this particular one could definitely be clearer. Unfortunately we don't have direct control over this content, as these docs are derived [from the Terraform provider](https://registry.terraform.io/providers/hashicorp/aws/3.74.3/docs/resources/apigatewayv2_route#import), so a change would need to be made to the content in that repository (e.g., [here](https://github.com/hashicorp/terraform-provider-aws/blob/3cefc94bf74beff98c4982a274aedd4560288992/website/docs/r/apigatewayv2_route.html.markdown?plain=1#L97)) to address this particular instance (and [many others](https://github.com/search?q=repo%3Ahashicorp%2Fterraform-provider-aws%20aabbccddee%2F1122334&type=code), it seems.)
