### ISSUE TITLE
Broke import on all docs

### ISSUE THREAD

**Issue by ami-descope** [pulumi/registry#3059]
File: [themes/default/content/registry/packages/aws/api-docs/rds/cluster/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/rds/cluster/)

```
Import
terraform import {

to = aws_rds_cluster.aurora_cluster

id = “aurora-prod-cluster” } Using pulumi import, import RDS Clusters using the cluster_identifier. For exampleconsole % pulumi import aws_rds_cluster.aurora_cluster aurora-prod-cluster
```

**Comment by cnunciato** [comment]
Now I see. It looks like between the time this issue was submitted and when we reviewed it (after the break), like this issue was momentarily "fixed", presumably by reverting the AWS 6 release. We're now seeing it resurface: https://github.com/pulumi/pulumi-terraform-bridge/issues/1344

**Comment by toriancrane** [comment]
As of today, it looks like this issue is no longer present:

![image](https://github.com/pulumi/registry/assets/19211559/0ff3ad16-3008-403e-892d-476482b119a8)

Should we close as no-repro?

**Comment by ami-descope** [comment]
Sure close it
