### ISSUE TITLE
maybe i think your documentation lags

### ISSUE THREAD

**Issue by dalailama83** [pulumi/registry#3088]
File: [themes/default/content/registry/packages/gcp/api-docs/serviceAccount/getaccount/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/getaccount/)

getaccount has more then 2 parameter and does not works as expected for me.

**Comment by cnunciato** [comment]
Closing this as it's unclear what's to be done, but feel free to reopen with additional details as to what didn't work and what you expected, and we'll have a look!
