### ISSUE TITLE
Web page out of date: https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/

### ISSUE THREAD

**Issue by ygyg70** [pulumi/registry#3092]
### What happened?

[https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/](https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/)
The code is using outdated APIs, such as awsx.elasticloadbalancingv2.NetworkListener

### Expected Behavior

The code in the page should either be correct or removed

### Steps to reproduce

Open https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/ in a browser, try to follow the example 

### Output of `pulumi about`

not relevan

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by toriancrane** [comment]
We can actually close this one as [this PR](https://github.com/pulumi/registry/pull/3065) fixed it (I forgot to set auto-merge, but it should be merged now).
