### ISSUE TITLE
Clicking on an element in the filter navigation for API docs doesn't navigate

### ISSUE THREAD

**Issue by leezen** [pulumi/registry#315]
When using the API filter view, if I click on the text, it works. But if I happen to click "off to the side" (but still on a particular node in the filter view), it will highlight that node, but not navigate to the selected node.

**Comment by susanev** [comment]
context here: https://github.com/pulumi/theme/pull/31 it was expanded but does not match 100% currently

**Comment by susanev** [comment]
yah @EvanBoyle i think this might have regressed in ur pr
