### ISSUE TITLE
digitalocean.Droplet image is invalid

### ISSUE THREAD

**Issue by Arvind644** [pulumi/registry#3404]
### Problem description

The image name in pulumi registry digitalocean droplet is not working. <https://www.pulumi.com/registry/packages/digitalocean/api-docs/droplet/> .
Its giving  `You specified an invalid image for Droplet creation` error

### Suggestions for a fix

Please change the image from `ubuntu-18-04-x64` to `ubuntu-20-04-x64`

**Comment by cnunciato** [comment]
Fixed via https://github.com/digitalocean/terraform-provider-digitalocean/commit/1124e8761e8257521981786a63c1eff18de6e29d.
