### ISSUE TITLE
Lambda Function API example missing langchooser and out of place

### ISSUE THREAD

**Issue by joeduffy** [pulumi/registry#3498]
I am 50% certain this bug is already filed elsewhere but I can't find it.

If you go to this section https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#cloudwatch-logging-and-permissions, you will see that the first "example" is 1) not underneath the Example Usage section and 2) lacks a language chooser, so that all language examples are just stacked atop one another.

I believe the root cause ultimately comes down to [the source Markdown](https://raw.githubusercontent.com/hashicorp/terraform-provider-aws/main/website/docs/r/lambda_function.html.markdown) using a peer H2 for that section, alongside Example Usage, even though that H2 comes after the Example Usage one.

The result is ultimately that [registrygen](https://github.com/pulumi/registrygen) code-gens the wrong thing via [this template](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/templates/resource.tmpl). More precisely, it code-gens the right thing in that this is how everything is wired up, but I don't think that's what we want to do. The odd thing is that we did recognize and convert the code samples, it's just the way all of this docsgen gunk works is that it only recognizes a subset of those examples.

It does make me wonder ... are we just fundamentally swimming upstream with this approach? Should we instead simply preserve all H2s, in order, except for the highly structured sections like Argument and Attribute References, and preserve those in the front matter in their entirety, along with lang-choosers for every code example we encounter in the Markdown translation?

**Comment by toriancrane** [comment]
I think you are referring to [this one](https://github.com/pulumi/pulumi-aws/issues/2624).

**Comment by joeduffy** [comment]
Thanks Torian, that's the one, and the broader [epic](https://github.com/pulumi/pulumi-terraform-bridge/issues/1291) too.
