### ISSUE TITLE
The example is not working

### ISSUE THREAD

**Issue by rodrigobrim** [pulumi/registry#365]
File: [themes/default/content/registry/packages/aws/api-docs/getavailabilityzones/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/getavailabilityzones/)

```
localhost:~//pulumi/aws/k8s$ pulumi up
Previewing update (dev):
     Type                 Name     Plan     Info
     pulumi:pulumi:Stack  k8s-dev           1 error; 2 messages
 
Diagnostics:
  pulumi:pulumi:Stack (k8s-dev):
    # k8s
    ./main.go:12:52: undefined: GetAvailabilityZonesArgs
 
    error: an unhandled error occurred: program exited with non-zero exit code: 2
 
localhost:~/pulumi/aws/k8s$
```

Please provide instruction on how to define GetAvailabilityZonesArgs.

**Comment by leezen** [comment]
Unfortunately, this is due to https://github.com/pulumi/docs/issues/6853
If you prefix the type `GetAvailabilityZonesArgs` with `aws` as `aws.GetAvailabilityZonesArgs` then the example should compile.
