### ISSUE TITLE
api nav has extra space when no modules

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#371]
## overview
when a package has no modules, we still leave the space for the expand/collapse icon.

### screenshot
<img width="341" alt="extra-space" src="https://user-images.githubusercontent.com/5489125/142233875-cc36115e-2498-4dc2-b372-854d03ba238f.png">

## expected
when no modules exist in a package we reclaim the space for the expand/collapse icon so there is more space for the names in the nav

**Comment by susanev** [comment]
@anita-trimbur whereever the epic is for redesigning this nav, can you add this issue to it? thank you!

**Comment by cnunciato** [comment]
@anita-trimbur Would you say this is still an issue? If looks like with the recent changes, the situation's improved for this, but I'm not sure it's quite done-done. What do you think?

**Comment by anita-trimbur** [comment]
@cnunciato yeah the spacing referenced here was essentially "fixed" with the introduction of the left nav across registry. the part that's not quite resolved imo is we expected to eventually move away from using a lettered icon on every line which would help in significantly reducing the line length. we might be better served just creating a new issue to that effect though.

**Comment by cnunciato** [comment]
Sounds good, thanks. I'll close this, then, and we can file a new one for the icons. Thanks!
