### ISSUE TITLE
Overview docs missing Java and YAML example for pulumi-hcloud

### ISSUE THREAD

**Issue by hrstoyanov** [pulumi/registry#3895]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by iwahbe** [comment]
It seem slike this is a common problem, not limited `pulumi-hcloud`. Of the first 10 [providers](https://www.pulumi.com/registry/) (sorted a-z) owned by pulumi, 8 of them were missing at least Java or Yaml from their main page. 8/10 were missing Java and 6/10 were missing YAML.

| Provider                     | Java | YAML |
|------------------------------|------|------|
| Aiven                        | No   | No   |
| Akamai                       | No   | No   |
| Alibaba Cloud                | No   | No   |
| Amazon EKS                   | Yes  | Yes  |
| Artifactory                  | No   | No   |
| Auth0                        | No   | No   |
| Pulumi Auto Deploy (preview) | No   | Yes  |
| AWS API Gateway              | No   | No   |
| AWS Classic                  | Yes  | Yes  |
| AWS IAM                      | No   | Yes  |

**Comment by guineveresaenger** [comment]
This has been fixed via https://github.com/pulumi/pulumi-hcloud/pull/599.

Several of the other providers (Aiven, Alicloud, Artifactory, Auth0) have also been fixed via efforts in https://github.com/pulumi/home/issues/3598 as well.

Closing this issue as the original scope of the ticket was fixed and it appears actively maintained Pulumi providers are showing Java and YAML.

Please open new tickets tracking individual providers if similar issues crop up.
