### ISSUE TITLE
CLI import docs references ID but that's not always the case

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/registry#3908]
### Problem description

Both the [import guide](https://www.pulumi.com/docs/guides/adopting/import/) and the [CLI import docs](https://www.pulumi.com/docs/reference/cli/pulumi_import/) talks about IDs that are returned, but that's not always the case. 

Example is this resource: https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webappswiftvirtualnetworkconnection/

The value that is returned from Azure that we store as the ID isn't the same as the identity that you need to import this resource.

I propose changing the references on this page about "ID" to "identity" instead.

**Comment by cnunciato** [comment]
@pierskarsenbarg With #3992, I updated most of this doc, and part of what I did was to make this concept of "which ID do I use?" a little clearer by clarifying that the value used to look up a resource varies by provider. I'll therefore close this as complete with that work, but if after reading it you have any suggestions, I'm absolutely happy to make them. Feel free to post back here in a comment if it's something simple or by reopening if you feel like the changes I've made still fall short here. Thanks!
