### ISSUE TITLE
Missing spec for visibilityConfig in AWS CloudWatch metrics page

### ISSUE THREAD

**Issue by jamest-pin** [pulumi/registry#3909]
File: [themes/default/content/registry/packages/aws/api-docs/wafv2/webacl/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/wafv2/webacl/)

I'm reading here: [visibilityConfig](https://www.pulumi.com/registry/packages/aws/api-docs/wafv2/webacl/#visibilityconfig_yaml)

> This property is required.
> [Property Map](https://www.pulumi.com/registry/packages/aws/api-docs/wafv2/webacl/#webaclvisibilityconfig)
> Defines and enables Amazon CloudWatch metrics and web request sample collection. See visibility_config below for details.

But there is nothing below. I have searched for 'visibility' , 'metric' , and 'sample' and no useful hits on the page.

Clicking the 'Property Map' hyperlink goes nowhere
![image](https://github.com/pulumi/pulumi-hugo/assets/138646078/15489e14-fa84-4f2e-a1aa-20fe6acd1d0b)

Here is equivalent terraform config
![image](https://github.com/pulumi/pulumi-hugo/assets/138646078/eda9c025-5017-409f-a6fd-82b57a2569ef)

Thanks

**Comment by sean1588** [comment]
It looks like this may have resolved itself. It looks like there are now specific types defined for these supporting types and the linking is behaving correctly.

<img width="745" alt="Screen Shot 2024-02-14 at 1 17 17 PM" src="https://github.com/pulumi/registry/assets/16751381/c97a8255-3b9e-4b3b-b888-1f3d2c1fd992">

**Comment by sean1588** [comment]
going to go ahead and close this out since this seems to be resolved for the specific case called out by this issue
