### ISSUE TITLE
Spike on emitting JSON from sdkgen and consumption from registry

### ISSUE THREAD

**Issue by sean1588** [pulumi/registry#3918]
Spike on emitting JSON from pulumi/pulumi codegen. Ideally get this running alongside the current markdown generation process so we can gradually transition off of it while updating other tooling.

**Comment by sean1588** [comment]
related to resolving: https://github.com/pulumi/pulumi/issues/14675

**Comment by cnunciato** [comment]
Closing as wontfix, but we can revisit this when the time comes!
