### ISSUE TITLE
Move examples further down on the docs page

### ISSUE THREAD

**Issue by sean1588** [pulumi/registry#3929]
Move examples to further down on the docs page. Currently they are the first to display after the resource's description. They should follow after the input/output properties section.

**Comment by lukehoban** [comment]
I'm not apriori sure this is a good thing.  I would argue the examples are the highgest used part of these pages, and if anything, the fact that we have them collapsed by default actually is limiting usability of the pages overall.

**Comment by toriancrane** [comment]
I believe the addition of a complete/syntactically correct resource definition would provide greater value being higher on the page given that the examples are often not comprehensive of all available input properties/configurations. There are also more [pedagogical benefits](https://docs.google.com/document/d/1Coc4UxOGU6O_c0JdrjenYv4cKJZOXDjlt6ZbV4UZoXc/edit#heading=h.6sqdjjo4zl3j) in this approach as well.

**Comment by toriancrane** [comment]
> I'm not apriori sure this is a good thing. I would argue the examples are the highgest used part of these pages, and if anything, the fact that we have them collapsed by default actually is limiting usability of the pages overall.

I believe the addition of a complete/syntactically correct resource definition would provide greater value being higher on the page given that the examples are often not comprehensive of all available input properties/configurations. There are also more [pedagogical benefits](https://docs.google.com/document/d/1Coc4UxOGU6O_c0JdrjenYv4cKJZOXDjlt6ZbV4UZoXc/edit#heading=h.6sqdjjo4zl3j) in this approach as well.

**Comment by iwahbe** [comment]
The registry does not control where examples are displayed in the body of resources. If we want to take this (and I'd argue we don't), then we would need to take it in the bridge.
