### ISSUE TITLE
documentation on pulumi registry needs updating - config vs getconfig

### ISSUE THREAD

**Issue by lethargosapatheia** [pulumi/registry#3954]
## Hello!

There's deprecated and misleading information in the documentation.

## Issue details

In the Overview section of https://www.pulumi.com/registry/packages/cloudinit/ `Config` is being used. But `Config` is deprecated as mentioned in the `Config` section (https://www.pulumi.com/registry/packages/cloudinit/api-docs/config/).

As far as I understand, only `getConfig` is supposed to be used, but I'm still not clear, given the deprecation message:
> This resource is deprecated Please use the cloudinit.Config data source instead.

**Comment by guineveresaenger** [comment]
This is fixed via https://github.com/pulumi/pulumi-cloudinit/pull/390. 🎉
