### ISSUE TITLE
Fix deprecation message rendering

### ISSUE THREAD

**Issue by sean1588** [pulumi/registry#3972]
I am 99% sure there is already an issue for this, but I cannot seem to track it down. Deprecation messages sometimes render strangely outside of its formatted box:

<img width="624" alt="Screen Shot 2024-02-14 at 1 51 50 PM" src="https://github.com/pulumi/registry/assets/16751381/9034eaff-2cec-44d8-ba99-2eb42cf86612">

**Comment by sean1588** [comment]
After doing a bit of investigation it looks like the trailing "\n" from the property description messes with the markdown rendering. After removing it the text appears correctly in the box, but we loose the description formatting. I'm looking into a solution here.

**Comment by ericrudder** [comment]
this has definitely been reported multiple times (including once by me!)
... https://github.com/pulumi/registry/issues/3008 is one example if you're
looking for previous fix attempts at similar stuff

**Comment by sean1588** [comment]
thank you @ericrudder, I'll take a look at that.
