### ISSUE TITLE
Can't export kubeconfig when following the guide with AKS via C#

### ISSUE THREAD

**Issue by d1mnewz** [pulumi/registry#409]
File: [themes/default/content/registry/packages/azure-native/how-to-guides/azure-cs-aks.md](https://www.pulumi.com/registry/packages/azure-native/how-to-guides/azure-cs-aks/)

![image](https://user-images.githubusercontent.com/11834902/143042496-8e6a028c-22ba-4d41-812c-065b7d6865cf.png)

Issue when following this guide:

> dimko@DESKTOP-KVKFCQP:~/.pulumi/test/azure-cs-aks$ pulumi stack output kubeconfig --show-secrets > kubeconfig.yaml
> error: current stack does not have output property 'kubeconfig'

It's gotta be 
> pulumi stack output KubeConfig --show-secrets > kubeconfig.yaml

since property name is case sensetive. 

![image](https://user-images.githubusercontent.com/11834902/143042900-3eaf1234-647d-49c6-b797-6cd1b73eda57.png)

**Comment by mikhailshilkov** [comment]
@d1mnewz I believe the correct capitalization with the current code is `KubeConfig`, so 

```
pulumi stack output KubeConfig --show-secrets > kubeconfig.yaml
```

I'll fix the example to change the output to lowercase.

**Comment by d1mnewz** [comment]
well done @mikhailshilkov thanks
