### ISSUE TITLE
Malformed examples on aws.alb.LoadBalancer page

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#4161]
The Go,C#, and Java examples on this page are getting mangled: 

https://www.pulumi.com/registry/packages/aws/api-docs/alb/loadbalancer/

![image](https://github.com/pulumi/registry/assets/274700/ba44d1ff-d70b-4e1f-bad6-b895ba46df78)

Reported in Community Slack: https://pulumi-community.slack.com/archives/CRH5ENVDX/p1710840502278839

**Comment by cnunciato** [comment]
It'd also be great if we could get an e2e test in place to cover this sort of issue before closing it out.

**Comment by iwahbe** [comment]
I missed the API docs meeting last week. Do we believe that this is a bug in the bridge, pulumi/pulumi or in the registry?

**Comment by sean1588** [comment]
I believe this should actually be resolved now, but will confirm with the next release.

**Comment by sean1588** [comment]
This is has been fixed, so closing out.
