### ISSUE TITLE
Configuration example is not good

### ISSUE THREAD

**Issue by alexandrelussier** [pulumi/registry#425]
File: [themes/default/content/registry/packages/azure-native/installation-configuration.md](https://www.pulumi.com/registry/packages/azure-native/installation-configuration/)

Since the provider is azure-native we should read:
`pulumi config set azure-native:clientId <clientID>
pulumi config set azure-native:clientSecret <clientSecret> --secret
pulumi config set azure-native:tenantId <tenantID>
pulumi config set azure-native:subscriptionId <subscriptionId>`

instead of 
`pulumi config set azure:clientId <clientID>
pulumi config set azure:clientSecret <clientSecret> --secret
pulumi config set azure:tenantId <tenantID>
pulumi config set azure:subscriptionId <subscriptionId>`

**Comment by susanev** [comment]
@alexandrelussier thanks for reporting this!! would you be up for submitting a pr?
https://github.com/pulumi/registry/edit/master/themes/default/content/registry/packages/azure-native/installation-configuration.md

**Comment by alexandrelussier** [comment]
@susanev done: https://github.com/pulumi/registry/pull/436
