### ISSUE TITLE
EKS Nodegroups documentation, not showing Inputs/Outputs

### ISSUE THREAD

**Issue by axblum** [pulumi/registry#4313]
File: [themes/default/content/registry/packages/aws/api-docs/eks/nodegroup/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/eks/nodegroup/)

Outputs and Inputs are missing from this resource type.

**Comment by t0yv0** [comment]
Thank you @sean1588 !

**Comment by sean1588** [comment]
@axblum - the fix is now released and this is now resolved, so going to close it out!! https://www.pulumi.com/registry/packages/aws/api-docs/eks/nodegroup/ 

cc @t0yv0  @corymhall

**Comment by axblum** [comment]
Thanks for the quick fix!
