### ISSUE TITLE
documentation - namespace description is incorrect

### ISSUE THREAD

**Issue by mortaelth** [pulumi/registry#441]
File: [themes/default/content/registry/packages/kubernetes/installation-configuration.md](https://www.pulumi.com/registry/packages/kubernetes/installation-configuration/)

**Comment by susanev** [comment]
@mortaelth would you be up for submitting a pull request?
https://github.com/pulumi/registry/edit/master/themes/default/content/registry/packages/kubernetes/installation-configuration.md

**Comment by lblackstone** [comment]
Fixed in https://github.com/pulumi/registry/commit/dbad203c900a5cb4836823c1ea2e7e91c6c059c3
