### ISSUE TITLE
resourcedocsgen README: installation instructions need update

### ISSUE THREAD

**Issue by thomas11** [pulumi/registry#4413]
### What happened?

The README says
>You can install the resourcedocsgen tool just like any other Go-based CLI tool:
> `go install github.com/pulumi/docs/tools/resourcedocsgen@master`

But:
```
❯ go install github.com/pulumi/docs/tools/resourcedocsgen@master
go: downloading github.com/pulumi/docs v0.0.0-20240428120206-4d5b33b8ce1e
go: github.com/pulumi/docs/tools/resourcedocsgen@master: module github.com/pulumi/docs@master found \
  (v0.0.0-20240428120206-4d5b33b8ce1e), but does not contain package github.com/pulumi/docs/tools/resourcedocsgen
```

### Example

see above

### Output of `pulumi about`

Master branch at commit 2cbabd0f3884954aad7abfe89a13bf153cd51df2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by sean1588** [comment]
thanks @thomas11. Looks like this is needs to be updated. The tool now lives in registry, not the docs repo anymore.  I'll get this updated.

just swapping out `docs` for `registry` should work:
```
go install github.com/pulumi/docs/tools/resourcedocsgen@master
```
