### ISSUE TITLE
Automatically generate installation & configuration

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/registry#449]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In order to keep the configuration options in-sync, could we automatically generate the installation and configuration options page to reduce the number of areas we need to manually write?

### Affected area/feature

- Installation & configuration pages for each provider

**Comment by jkodroff** [comment]
Seconding this. We might also go a step further and unify the experience between "installation and configuration" and `package.Provider`, maybe not keep them as separate pages.

**Comment by iwahbe** [comment]
We have moved to allow publishing only an `_index.md`, which is auto-generated for many providers. We can't auto-generate installation configuration in the general case because we don't know how they should be consumer, which SDKs are published and where, etc.
