### ISSUE TITLE
correction to stackreference example step 5

### ISSUE THREAD

**Issue by onching** [pulumi/registry#471]
File: [themes/default/content/registry/packages/aws/how-to-guides/aws-ts-stackreference.md](https://www.pulumi.com/registry/packages/aws/how-to-guides/aws-ts-stackreference/)

step 5 copy box should be "department" instead of "company"
cd ../department
npm install

**Comment by susanev** [comment]
@onching thanks for reporting the issue!! we will take a look as soon as we can.
