### ISSUE TITLE
Fix use cases of aws components

### ISSUE THREAD

**Issue by clstokes** [pulumi/registry#489]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I expected the [AWS Quickstart VPC](https://www.pulumi.com/registry/packages/aws-quickstart-vpc/) to be listed when I filtered for `Type:Component` and `UseCase:Network`.
<img width="1050" alt="screenshot-2021-12-21-14-21-02@2x" src="https://user-images.githubusercontent.com/293763/147005206-2ee3f212-33ba-45c4-9bfe-afc0410613de.png">

### Steps to reproduce

1. go to https://www.pulumi.com/registry/
2. filter based on `Type:Component` and `UseCase:Network`

Expected: expect AWS QuickStart VPC to be listed
Actual: no results

**Comment by susanev** [comment]
looks like it has the use case of cloud, so it should be network instead?

**Comment by clstokes** [comment]
> looks like it has the use case of cloud, so it should be network instead?

Yes, I think so.

**Comment by susanev** [comment]
@clstokes should any of the other aws components change as well? they all look to have the cloud use case.

**Comment by clstokes** [comment]
> @clstokes should any of the other aws components change as well? they all look to have the cloud use case.

yep! I was just writing them up...

- [AWS QuickStart Aurora Postgres](https://www.pulumi.com/registry/packages/aws-quickstart-aurora-postgres/) should be `UseCase:Database`
- [AWS QuickStart Redshift](https://www.pulumi.com/registry/packages/aws-quickstart-redshift/) should be `UseCase:Database`

**Comment by kimberleyamackenzie** [comment]
Triage 12/21: Let's just fix these, but maybe moving forward we need more of a tagging scheme.
