### ISSUE TITLE
Critical failure to render docs

### ISSUE THREAD

**Issue by iwahbe** [pulumi/registry#5095]
### What happened?

A registry page has failed to render close to correctly.

My believe is that there is no level of broken provider docs that should result in this page.

### Example

Follow up on https://github.com/pulumi/pulumi-snowflake/issues/683.

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thoward** [comment]
related/dup: #5061

**Comment by iwahbe** [comment]
Looking at the failure at https://www.pulumi.com/registry/packages/rancher2/api-docs/nodetemplate/, I see this in the description:

```
    ## Upgrading to Rancher v2.3.3
    
    **Important** This process could update `rancher2.NodeTemplate` data on tfstate file. Be sure to save a copy of tfstate file before proceed
    
    Due to [this feature](https://github.com/rancher/rancher/pull/23718) included on Rancher v2.3.3, `rancher2.NodeTemplate` are now global scoped objects with RBAC around them, instead of user scoped objects as they were. This means that existing node templates `id` field is changing on upgrade. Provider implements `fixNodeTemplateID()` that will update tfstate with proper id.
    ```
```

The rendering error is almost certainly caused by the unclosed ``` bracket.

**Comment by iwahbe** [comment]
Both Github and the TF registry handle the extra ``` gracefully. It does not cause the entire page to mis-render. I think we will need to be able to degrade gracefully as well.

**Comment by interurban** [comment]
Thanks Ian; It would seem what you describe then would be related to this as well: https://github.com/pulumi/registry/issues/5033

**Comment by iwahbe** [comment]
It could very well be.
