### ISSUE TITLE
gcp.monitoring.AlertPolicy is missing `severity` field

### ISSUE THREAD

**Issue by xSAVIKx** [pulumi/registry#5107]
File: [themes/default/content/registry/packages/gcp/api-docs/monitoring/alertpolicy/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/monitoring/alertpolicy/)

The `severity` field is supported by SDKs but it is missing in `inputs` and overall in docs.

**Comment by cnunciato** [comment]
Thanks for filing this, @xSAVIKx! Looks like the `severity` input does exist as of now, so it may have been added with the latest release.

![Image](https://github.com/user-attachments/assets/86e9f1ad-12d3-4982-9cfa-02698c1d592f)

I'll therefore close this for now, but feel free to reopen if I've misunderstood and there's something more to be done here.
