### ISSUE TITLE
broken page title and links in how-to guide

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#513]
## overview
File: [themes/default/content/registry/packages/aws/how-to-guides/aws-py-apigateway-lambda-serverless.md](https://www.pulumi.com/registry/packages/aws/how-to-guides/aws-py-apigateway-lambda-serverless/)

randomly noticed this today...
### list page
<img width="536" alt="Screen Shot 2021-12-30 at 4 34 35 PM" src="https://user-images.githubusercontent.com/5489125/147796452-4afde157-2408-4e7d-829f-719e863712ca.png">

### detail page
<img width="985" alt="Screen Shot 2021-12-30 at 4 34 44 PM" src="https://user-images.githubusercontent.com/5489125/147796450-93904607-34af-40bc-b3bf-8e0e0e296042.png">

**Comment by leezen** [comment]
Looks like this is actual content from the example itself: https://github.com/pulumi/examples/tree/master/aws-py-apigateway-lambda-serverless
