### ISSUE TITLE
Rancher2 Node Template docs are broken

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/registry#5136]
### What happened?

Go to: https://www.pulumi.com/registry/packages/rancher2/api-docs/nodetemplate/

Looks like this: 

![Image](https://github.com/user-attachments/assets/51c7be63-5042-4c48-b366-2cccc025005b)

### Example

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
This will hopefully be fixed by the next bridge release. 

Related to https://github.com/pulumi/registry/issues/5095
