### ISSUE TITLE
Indicate which resource properties cause replacement

### ISSUE THREAD

**Issue by joeduffy** [pulumi/registry#518]
It would be handy if we indicated in the API docs for resources which properties, if changed, will trigger a replacement.

This is similar to the AWS CloudFormation docs; for instance, see [_"Update requires"_ on this page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.htm). We can clearly see, for instance, that changing `BucketName`, `ObjectLockEnabled`, etc, triggers "replacement" whereas most properties are marked "no interruption."

So as not to clutter up things, we could use a special marker such as ⚠️ or `!`, similar to what we do for required properties:

![image](https://user-images.githubusercontent.com/3953235/147835286-840fa656-9ab8-47a4-8cac-ac603e064f75.png)

We should have all the metadata we need to know this, and surprisingly don't seem to surface it anywhere as far as I can tell.

**Comment by susanev** [comment]
happy to help someone come up with an icon for this. id recommend against using the warning icon though since that has a particular use case which i don't believe is the same as this situation.

here's an example of an icon that may work, but also happy to create something custom for this.
![icon](https://user-images.githubusercontent.com/5489125/147840150-3fc5efe5-c9c0-48c0-872b-694d1c0feda7.png)

**Comment by susanev** [comment]
@jkisk is it possible for something to be both required and cause a replacement?

**Comment by susanev** [comment]
@kimberleyamackenzie what do you think the eng effort will be to make this happen?

**Comment by susanev** [comment]
@lukehoban where should i add an issue for that?

**Comment by jkisk** [comment]
@susanev I believe the answer is yes that something can be required and trigger a replacement, so probably both icons will need to be displayed.  The example that came to mind was secrets manager secrets: 

https://www.pulumi.com/registry/packages/aws/api-docs/secretsmanager/secret/
https://docs.aws.amazon.com/secretsmanager/latest/userguide/manage_update-secret.html

In that example the name field is required but not modifiable.

**Comment by susanev** [comment]
https://github.com/pulumi/pulumi/pull/9603 has been released so we can pick this back up and its no longer blocked

**Comment by susanev** [comment]
this has been merged. it will show up only on snowflake now, and other providers once they are updated.
