### ISSUE TITLE
Multiple provider package pages are blank

### ISSUE THREAD

**Issue by interurban** [pulumi/registry#5267]
### What happened?

Looking at some of our provider pages, they are no longer displaying any content: 
Spot checking a few, I'm sure there would be others impacted.

Avian - https://www.pulumi.com/registry/packages/aiven/
Auth0 - https://www.pulumi.com/registry/packages/auth0/
Cloudflare - https://www.pulumi.com/registry/packages/cloudflare/

### Example

Auth0 - https://www.pulumi.com/registry/packages/auth0/
Cloudflare - https://www.pulumi.com/registry/packages/cloudflare/

### Output of `pulumi about`

n/a

**Comment by aaronkao** [comment]
Other pages affected:

- https://www.pulumi.com/registry/packages/consul/
- https://www.pulumi.com/registry/packages/alicloud/
- https://www.pulumi.com/registry/packages/datadog/
- https://www.pulumi.com/registry/packages/digitalocean/
- https://www.pulumi.com/registry/packages/dnsimple/
- https://www.pulumi.com/registry/packages/openstack/

**Comment by guineveresaenger** [comment]
Fixed in https://github.com/pulumi/registry/pull/5278.

Needs followup in individual providers.
