### ISSUE TITLE
AWS API Gateway MLC examples not listed

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/registry#530]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

There are 3 examples written for the `aws-apigateway` package but they don't appear within the registry [aws-apigateway how to guides](https://www.pulumi.com/registry/packages/aws-apigateway/how-to-guides/).

Expected examples to be shown:

1. https://github.com/pulumi/examples/tree/master/aws-apigateway-go-routes
2. https://github.com/pulumi/examples/tree/master/aws-apigateway-py-routes
3. https://github.com/pulumi/examples/tree/master/aws-apigateway-ts-routes

Not sure if there's another step required to get the examples tied to the provider.

**Comment by cnunciato** [comment]
The reason for these not appearing may have to do with the naming: it should be `[cloud]-[language]-[everything-else]`.

**Comment by cnunciato** [comment]
... and now I realize you probably _don't_ want these appearing under `aws`, so in that case, disregard. 😄  🤦‍♂️

**Comment by susanev** [comment]
oh man i was so confused for a minute...

**Comment by cnunciato** [comment]
Here's a PR that may fix it up -- running a preview now to see how things look (appears to have been a while since we did this): https://github.com/pulumi/docs/pull/6996

We [hard-code the list of packages to filter for](https://github.com/pulumi/docs/blob/master/scripts/mktutorial.sh#L7), so in this case, we were actually generating them, just not copying them back into the repo afterwards.

**Comment by susanev** [comment]
@cnunciato wont we at some point want all the packages in the hard-coded list?

**Comment by cnunciato** [comment]
> wont we at some point want all the packages in the hard-coded list?

It'd probably make sense to just pick all up examples automatically, so we don't even have to hard-code anything, yeah. I don't think we're quite there yet, but I'm happy to file an issue to start taking steps toward having this all "just work". Hopefully I'm answering your question, here. 😄

**Comment by susanev** [comment]
sure yes, thank you. we should maybe try and document this additional step for now so other folks in Daniels situation has at least some guidelines on how to get their examples to show up.
