### ISSUE TITLE
Replace `serviceAccount` with `serviceaccount`

### ISSUE THREAD

**Issue by vschettino-asimov** [pulumi/registry#544]
The module name in the basic example is wrongly capitalized as `serviceAccount`. It should be `serviceaccount`. I can open a PR to fix that if it's a good idea.

File: [themes/default/content/registry/packages/gcp/api-docs/serviceAccount/account/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/)

**Comment by leezen** [comment]
@vschettino-asimov Thanks for offering to PR. This is a problem with the code generator (the example is automatically generated), so unfortunately we'll need to fix this in a different way. We're currently tracking this in https://github.com/pulumi/pulumi-hugo/issues/477
