### ISSUE TITLE
difference between Azure-classic and Azure-native is unclear and confusing for new people

### ISSUE THREAD

**Issue by bowdenk7** [pulumi/registry#547]
File: [themes/default/content/registry/packages/azure/api-docs/appservice/plan/_index.md](https://www.pulumi.com/registry/packages/azure/api-docs/appservice/plan/)

The example only has `tier` and `size`, but when I try to use that I get the error:

```
azure-native:web:AppServicePlan (server-plan):
    error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: Required property 'name' not found in 'sku'."
    ```

**Comment by bowdenk7** [comment]
I'm wrong - apparently I was looking at Azure-classic not Azure-native. This is super confusing for a new user. Feels like yall should put a banner at the top that redirects people to Azure-native. 

Especially when searching for something like "pulumi azure app service plan" takes you to classic as the first result.
<img width="964" alt="Screen Shot 2022-01-12 at 1 02 39 PM" src="https://user-images.githubusercontent.com/820883/149205139-008a90b3-ec93-4e33-91c4-a355d4fc412f.png">

**Comment by susanev** [comment]
@bowdenk7 ah i see, sorry about that! we do have a note on the [overview page of the classic provider](https://www.pulumi.com/registry/packages/azure/) but we can do better here. 

ive opened up https://github.com/pulumi/pulumi-hugo/issues/965 to track improvements here, so im going to close this out.
