### ISSUE TITLE
Some metadata files don't contain proper package titles

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#562]
Some packages aren't listed with proper names on the index page. For example:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/274700/149643357-88d016a5-6e6e-4e8b-9c6f-68e4554fd3f1.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/274700/149643359-b15cf403-4833-4275-88a5-db8476f951b9.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/274700/149643386-1070262c-50dc-46cf-994f-864ba22c508e.png">

<img width="421" alt="image" src="https://user-images.githubusercontent.com/274700/149643392-59a0892c-409d-434d-b7ab-79a9d382c3eb.png">

However, their corresponding pages look right:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/274700/149643410-c7e939f0-fa71-4c14-b4c1-8a0302deceae.png">

<img width="471" alt="image" src="https://user-images.githubusercontent.com/274700/149643418-539bda60-d983-4c07-bdf1-664d443f2edf.png">

<img width="459" alt="image" src="https://user-images.githubusercontent.com/274700/149643421-67312fac-78a9-4e80-872a-e0c39efb59c1.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/274700/149643425-b3ee246c-65ab-4099-82c1-59c59292442c.png">

We should fix these up and update the metadata automation so the YAML files contain the titles as well, so these two are always in sync.

**Comment by cnunciato** [comment]
@praneetloke Any tips on how to make this happen?

**Comment by praneetloke** [comment]
@cnunciato I have a hunch as to what's going on but taking a look to see what it is...

**Comment by cnunciato** [comment]
Awesome, thanks!
