### ISSUE TITLE
Redeploy Service On Every Apply - does not exists in pulumi

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/registry#5687]
File: [themes/default/content//registry/packages/aws/api-docs/ecs/service](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/service/)

This whole snippet is "copied" from Terraform docs but there's no alternative in pulumi, nor the term `apply` exists.
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const example = new aws.ecs.Service("example", {
    forceNewDeployment: true,
    triggers: {
        redeployment: "plantimestamp()",
    },
});
```

**Comment by thoward** [comment]
Thanks for filing an issue on this! Right now there's not a way to directly fix this documentation issue, but I'll share this feedback with the Terraform bridge engineering team to see if there's a way to enhance that process in the future.
