### ISSUE TITLE
Add an example of using the Command package

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#579]
It'd be great to have an example (a proper one sourced from pulumi/examples, flowing into Registry) of how to use this package across multiple languages and clouds.

**Comment by susanev** [comment]
the plan for examples is here: https://github.com/pulumi/pulumi-command/issues/11
in case that's helpful to you

**Comment by iwahbe** [comment]
I'm closing this out as completed. We have good examples in every language.
