### ISSUE TITLE
update the index.ts on "How-to Guides" EKS Page

### ISSUE THREAD

**Issue by jakobkahf** [pulumi/registry#6083]
File: [themes/default/content//registry/packages/kubernetes/how-to-guides/eks](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/eks/)

The code snippet of "index.ts" is obsolete in the following step "Create a new EKS cluster-> Open the existing file index.ts, and replace the contents with the following"

please update the code snippet.

**Comment by mjeffryes** [comment]
Thanks for letting us know!
