### ISSUE TITLE
Add a filter for name on the list of providers

### ISSUE THREAD

**Issue by jkodroff** [pulumi/registry#657]
I'd love us to add a simple text filter to the registry homepage that would allow me to search for a provider by name. I think it should be leftmost field, since it's how I imagine most users would want to filter the list (to the left of the drop-down that says "Type" below:

<img width="1578" alt="image" src="https://user-images.githubusercontent.com/410614/155155126-cb4a9996-14b7-4feb-9ae5-b050d21fad8e.png">

Typing in the field would filter the list of providers displayed below (with an appropriately short de-bounce period).

I filed another issue (#558) around the same use case (quickly navigating to a provider's homepage), but this one is probably significantly easier to implement, and if we could blast it out, I'd be a happy camper indeed!

**Comment by susanev** [comment]
i swear we had an issue for this but I can't find it, it's been requested by a bunch of folks.

**Comment by anita-trimbur** [comment]
## [figma file](https://www.figma.com/file/bVEoSwAvU7KDpuPNri332F/Compact-Registry?node-id=167%3A3033)

## designs
<img width="1728" alt="name filter" src="https://user-images.githubusercontent.com/97129308/199557011-bbee2951-482b-4a0f-bd04-9a6ba0603b19.png">

## changes

* adds text filter below "type" and "use case" dropdowns
* should behave the the API docs text filter does now (auto filters results as user types, needs more than 1 character to begin filtering, shows "x" in text field to clear filter, etc)

**Comment by susanev** [comment]
@anita-trimbur i think we should prolly have a label for this that's like name filter, instead of search since its only filtering on name and not an actual search.

you could also consider putting this next to the filters if you wanted and reposition the applied filters. up to you. but happy to do more of an overhaul of this section if you'd like.

**Comment by anita-trimbur** [comment]
to clarify, you're saying it'd be more accurate to change from "search package names..." to "filter package names..."?

i personally prefer the search stacked over the filters, but if you'd like to see it other ways, i can look into it.

**Comment by susanev** [comment]
as long as we think this will be usable, then happy to try it out, but do really think we should not be labeling it as search, as its not going to function like a search. we should make sure to qa how these things will interact with each other when their are filters applied.

**Comment by anita-trimbur** [comment]
oh i don't mind labeling it as a filter! that's my bad i keep saying "search" out of habit. but i will make sure to talk to sean about the interaction of these things just in case that poses an issue. 

i was asking above about the placement of the the name filter relative to the existing filters.

**Comment by jkodroff** [comment]
Suggestion: Can we put all 3 filter fields on the same horizontal line? It would tighten things up and I think it might look better.

Also would not mind seeing "Use Case" disappear. I don't think it's a useful field and it's not entirely accurate since e.g. Aiven is DBaaS, which makes it both "database" and "infrastructure" but it only shows under "infrastructure".
