### ISSUE TITLE
Formatting issues in the Random provider docs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/registry#747]
Something seems to have gone awry with the formatting in the Import section here:

https://www.pulumi.com/registry/packages/random/api-docs/randomstring/#import

![image](https://user-images.githubusercontent.com/274700/158711936-f8ce2d6d-719d-4300-89e7-1eaeb2bec7c7.png)

**Comment by jkodroff** [comment]
Looks like it got resolved: 

<img width="779" alt="image" src="https://user-images.githubusercontent.com/410614/190879143-f197c7a1-e09e-47a3-a2d9-c2d444ca29a6.png">
