### ISSUE TITLE
elastic name is wrong

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#839]
i thought this had been fixed, but i guess maybe not, 🤷 
but the elastic name is wrong
which means it doesn't come up in our search

<img width="649" alt="elastic-woes" src="https://user-images.githubusercontent.com/5489125/162816988-dd4d1b05-9ff3-42c9-9ff3-8725a96f9fbd.png">

**Comment by susanev** [comment]
seems to be right on the package page, just not the browse page

**Comment by stack72** [comment]
> i thought this had been fixed, but i guess maybe not, 🤷 but the elastic name is wrong which means it doesn't come up in our search
> 

What should it be called?

**Comment by susanev** [comment]
@stack72 on the package page the name is `ElasticCloud (EC)` can we match the name on the list page to that?

**Comment by jkisk** [comment]
Updating the provider's resources.go file to contain a DisplayName field should resolve this, is that correct @stack72 ?

**Comment by jkodroff** [comment]
@jkisk Looking at [DigitalOcean's resources.go](https://github.com/pulumi/pulumi-digitalocean/blob/master/provider/resources.go), I believe that you are correct: There is no field in the Pulumi provider config that controls the display text on the package page.

**Comment by susanev** [comment]
this is now fixed
