### ISSUE TITLE
gcp serviceaccount 404s

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#927]
this is part of https://github.com/pulumi/registry/issues/758
`https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount` 404s, but `serviceAccount` works
can we add an exception in the frontend so this works until we can fix the bigger issue?

**Comment by kimberleyamackenzie** [comment]
This was fixed by https://github.com/pulumi/docs/pull/7519
