### ISSUE TITLE
if a resource is named Index Hugo does weird things with it

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#951]
an example. if you interact with the firstore module it sends you to the index page.
if you interact with index it sends you to a 404.

<img width="287" alt="Screen Shot 2022-05-20 at 1 49 31 PM" src="https://user-images.githubusercontent.com/5489125/169608655-2ba13e38-56e4-4704-8732-d42ad36b9cdb.png">

the module page should be a list of links of the resources but hugo thinks because its named index, that its the index file

[internal slack convo](https://pulumi.slack.com/archives/C02R9QD1X17/p1653071649672009)

**Comment by cnunciato** [comment]
Sharing this in case it helps. We saw something like this last year (not sure when/why it resurfaced): https://github.com/pulumi/docs/issues/6206

As of now, when you run `make build` locally on the docs repo, you can see the difference between what gets generated, which looks right:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/274700/169658178-9fd663ab-c8e8-4e8f-9334-2852e796fbd5.png">

.. and what gets rendered:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/274700/169658225-7fa3d562-6447-4f2e-bf31-1233b0cdded8.png">

**Comment by susanev** [comment]
@kimberleyamackenzie i got a list of the pages broken by this through the seo tool, lets try and fix this in q1 when we are working on the api docs nav

<img width="1024" alt="index-issues" src="https://user-images.githubusercontent.com/5489125/206828364-3cf612ad-5331-4095-82b5-62df1cb3133b.png">

**Comment by sean1588** [comment]
changes are now live as of: https://github.com/pulumi/docs/pull/8480
