### ISSUE TITLE
Ref to aws_organizations_organization unfound from doc

### ISSUE THREAD

**Issue by BJoFRx00** [pulumi/registry#953]
Hello,
In typescript the doc use that ref but the result is infound.
File: [themes/default/content/registry/packages/aws/api-docs/organizations/organizationalunit/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/organizations/organizationalunit/)

error TS2304: Cannot find name 'aws_organizations_organization'.
Regards

**Comment by guineveresaenger** [comment]
Hi @BJoFRx00 - can you show us your code example, and share the output of `pulumi about` so we can investigate?

Also, are you asking about `OrganizationalUnit` or `Organization`? :)

Thank you!

**Comment by guineveresaenger** [comment]
Closing this in favor of https://github.com/pulumi/pulumi-aws/issues/1963
