### ISSUE TITLE
Verify that AWS Native, AWS Classic, Azure Native, Azure Classic, Google Native, Google Cloud Classic, and Kubernetes all show the appropriate user guides

### ISSUE THREAD

**Issue by infin8x** [pulumi/registry#98]

**Comment by susanev** [comment]
maybe related: https://github.com/pulumi/registry/issues/219

**Comment by djgrove** [comment]
> maybe related: #219

Closing the loop on this: this issue was related to our CloudFront redirect rules, and we've fixed it as of yesterday.

**Comment by susanev** [comment]
i have no idea if this was ever done, but it seems silly to keep around, so closing
