### ISSUE TITLE
Awsx sample is not valid

### ISSUE THREAD

**Issue by kimble** [pulumi/registry#990]
File: [themes/default/content/registry/packages/awsx/_index.md](https://www.pulumi.com/registry/packages/awsx/)

    const service = new awsx.ecs.FargateService("my-service", {
         cluster: cluster.arn  

The second line takes a cluster, not a string.

**Comment by stack72** [comment]
Hi @kimble 

We have acceptance tests around this code:

https://github.com/pulumi/pulumi-awsx/blob/master/examples/ts-lb-simple/index.ts#L11

https://github.com/pulumi/pulumi-awsx/runs/6621656312?check_suite_focus=true#step:20:287

The [docs](https://www.pulumi.com/registry/packages/awsx/api-docs/ecs/fargateservice/#cluster_nodejs) also point out that we expect the arn here as well

Paul

**Comment by cnunciato** [comment]
I believe it’s the beta package that takes an ARN, though; the currently released package does take a Cluster reference, and many new users seem to stumble on this.

We should probably make it clearer on these overview pages, and in the docs, that you need to install the beta to use these new APIs.
